### ISSUE TITLE
Antivirus detects `uv` installer as malicious on Windows

### ISSUE THREAD

**Issue by ShaiAvr** [astral-sh/uv#10079]
I wanted to give a try to `uv` to see if I like it as a project and dependencies manager. I tried installing it on my Windows 11 PC using the command: `powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"`
However, I get an error stating that this script contains malicious content and has been blocked by my antivirus software:

![Image](https://github.com/user-attachments/assets/ad5f17a0-b532-4137-8c30-5e194f41d5d9)
My antivirus (BitDefender) indeed believes this script is malicious:

![Image](https://github.com/user-attachments/assets/813413a9-7585-4efd-aa06-d208242e9303)
Why does this happen? How can I fix this and install `uv` on my Windows system?

**Comment by FishAlchemist** [comment]
I remember that the UV team actually couldn't do much about it, so you could try downloading the UV using other tools.

e.g. from PyPi
https://docs.astral.sh/uv/getting-started/installation/#pypi

**Comment by ShaiAvr** [comment]
Weird. Other tools like `pdm` and `rustup` also have installer scripts and I never had problems with them.

**Comment by FishAlchemist** [comment]
@ShaiAvr Perhaps the downloaded content triggered the virus detection? Since you're using a Windows 11 PC x86-64, this should be the correct link. Could you please scan this file?
https://github.com/astral-sh/uv/releases/download/0.5.11/uv-x86_64-pc-windows-msvc.zip

**Comment by zanieb** [comment]
Nothing we can do here but it submit it as valid software to the antivirus
 
- #4300
- #9144

**Comment by Stokestack** [comment]
For what it's worth, I just got the same thing:

<img width="528" height="271" alt="Image" src="https://github.com/user-attachments/assets/bf81643e-b39d-46fc-8836-9bd05364ec7e" />

**Comment by Rykarix** [comment]
I wouldn't be surprised if it's related to how uvx is the tool of choice for mcp servers which commonly demonstrate that you can run python code from anywhere by simply doing `uvx --from git+...`.

since ai + mcp server prolification I'm not surprised...


It's caused by `Smart App Control` which is part of windows (you can search for this by simply pressing the winkey and typing "Smart App Control". If you turn it off uv and others no longer get blocked but I don't recommend this for obvious reasons. Unfortunately windows doesn't appear to provide an obvious way to control this. Perhaps another user can offer a more sensible suggestion

**Comment by ojob** [comment]
My two cents, just for illustration to others: ESET also tagged `uv` as a "malicious, high-reputation-threat executable" in one of my CI pipelines, due to manipulation of hidden files, using `root:root`:

<img width="548" height="167" alt="Image" src="https://github.com/user-attachments/assets/0c1469d1-24fe-4f64-be26-3bd10a5b79f5" />

<img width="1126" height="77" alt="Image" src="https://github.com/user-attachments/assets/30206cf7-7c0f-4540-9d6f-0c30993d65c0" />

These hidden files are surely those from the Python virtual environments, aka. `.venv`, and `root` is used since it’s running in a container; said otherwise, `uv` does what it’s made for in an already contained environment.
