### ISSUE TITLE
`uv cache prune` doesn't remove packages from cache for deleted environments

### ISSUE THREAD

**Issue by neckbosov** [astral-sh/uv#10153]
Steps to reproduce:
```bash
mkdir $HOME/uv-test && cd $HOME/uv-test
export UV_CACHE_DIR=$HOME/uv-test/uv-cache
uv venv --python 3.9 ./python39env
VIRTUAL_ENV=./python39env uv pip install torch
du -hs ./uv-cache

uv venv --python 3.11 ./python311env
VIRTUAL_ENV=./python311env uv pip install torch
du -hs ./uv-cache

rm -rf ./python39env
uv cache prune
du -hs ./uv-cache
```

Expected result:
After pruning cache size will be the same as after the first installation.

Actual result:
`uv cache prune` doesn't delete anything, cache size stays the same as after the second installation.

uv version 0.5.10, fedora linux.

**Comment by charliermarsh** [comment]
What do you expect to be removed after `uv cache prune`?

**Comment by sh-shahrokhi** [comment]
> What do you expect to be removed after `uv cache prune`?

I have the same question. I though torch and its dependencies should be removed.

**Comment by neckbosov** [comment]
I would expect all packages installed for python 3.9 to be removed because they are no longer used in any of environments.

**Comment by QiE2035** [comment]
@charliermarsh 

[Translate from Chinese using Bing]

Referring to PDM, I think this can be done by adding a file on each cache item to keep track of where the cache is being used. I think this feature is still necessary to help find out which caches are no longer being used so that they can be cleaned or organized.
