### ISSUE TITLE
Make it available as a library

### ISSUE THREAD

**Issue by pomponchik** [astral-sh/uv#1375]
Hi!

I really like your idea of speeding up basic tooling for Python. It would also be very cool if you made `uv` available as a Python library that i can import into my Python source code.

I suppose there are many uses for this feature. Personally, I am the developer of the [`instld`](https://github.com/pomponchik/instld) - a wrapper around `pip` with superpowers. I am concerned about the slow speed of `pip` as a basic toolkit, and I would consider switching to `uv` in case it becomes possible to use it in library format.

**Comment by MichaReiser** [comment]
I like the idea of other tools using `uv` so that they benefit from the improved foundational tooling that we've built. However, I don't see us releasing an API soon because it will take us a while to reach a state where we feel comfortable committing to a stable API. Till then, I'm afraid the only option is to use the CLI.
