### ISSUE TITLE
Flag to allow `uv pip install` to install into specific environments (that do not necessarily contain uv)

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#1396]
It looks like `uv` already supports this, I just need to lie about `VIRTUAL_ENV`.

Looking for something like the equivalent of pip's `--prefix` or `--python`.

**Comment by RonNabuurs** [comment]
I did also encounter this when trying to use uv as a drop in replacement for my pip projects.

**Comment by ofek** [comment]
Definitely agree, this is fundamental to allow a single UV installation to be used as a real standalone binary!

**Comment by zanieb** [comment]
Yes we should support this. Is there a consensus on the name of the flag in other tools?

**Comment by ericbn** [comment]
pip has the `--require-virtualenv` option which makes it behave like uv:
```
$ pip install --require-virtualenv attrs
ERROR: Could not find an activated virtualenv (required).
```
but `--no-require-virtualenv` seems too long of a name for an option in uv. And sure the default uv behavior is much saner default!

**Comment by hauntsaninja** [comment]
[pip](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-prefix) uses `--prefix` and `--python` (I think the difference relates to which Python pip should be run with, which doesn't matter to uv).
[pypa/installer](https://installer.pypa.io/en/stable/cli/installer/) uses `--prefix`.

I'm not too familiar with pdm, but the `--venv` flag several of its command support is a name not a path (which is a good choice for high level workflow tool).

Meta since I got confused:
- There's maybe some overlap between this issue and https://github.com/astral-sh/uv/issues/1374 and https://github.com/astral-sh/uv/issues/1526 (which are duplicates of each other). In both cases the workaround is to set `VIRTUAL_ENV` explicitly.
- I view this issue as low priority and just providing a flag that does a very mechanical equivalent of `VIRTUAL_ENV=path uv pip install ...` via `uv pip install --prefix=path ...`
- The other issues is a flag that a) turns `uv pip install --prefix=$(python -c "import sys; print(sys.prefix)") ...` into `uv pip install --system ...`, b) promises that setting that flag will make things work for base Python, since it's not clear how intentional it is that setting `VIRTUAL_ENV` can let you point to a base Python. They also maybe need more thinking about how to identify the right base Python, e.g. if you do `python -m uv ...` should it look at `sys.base_prefix`?

**Comment by ofek** [comment]
> [pip](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-prefix) uses `--prefix` and `--python` (I think the difference relates to which Python pip should be run with, which doesn't matter to uv).

A few things:

1. The `--python` flag is desirable here because the tool that creates an environment is not necessarily the same program that uses an environment (perhaps in IDE). In this case, there is no knowledge of the base Python that was used and therefore no way to get information about its version, architecture, etc. It's not true to say that pip uses the flag to decide where to run (it's Python so it's already running) but rather it's entirely about information gathering.

    There is no way to avoid invoking the interpreter to get that data until [PEP 739](https://discuss.python.org/t/44572) is accepted (and implemented by various tools) and then another of the same kind for virtual environments is accepted (and implemented by various tools).
2. The `VIRTUAL_ENV` workaround indeed does not work well for base installations because the directory structure is not guaranteed and is often different based on the platform. For example, on Windows installations usually have a `python.exe` at the root whereas a virtual environment will have that under the `Scripts` directory. That command doesn't work in the official Python Docker image for instance:
    ```
    ❯ docker run --rm python:3.12 python -c "import sys; print(sys.prefix)"
    /usr/local
    ```

**Comment by hauntsaninja** [comment]
@ofek no, pip will literally run itself in a subprocess using a different interpreter: https://github.com/pypa/pip/blob/ebe491a82a13e6610697b22be00db363fb5ff5e3/src/pip/_internal/cli/main_parser.py#L82

**Comment by ofek** [comment]
Thanks for linking the code, I didn't realize that's how they chose to implement it! My point still stands in that pip is already running and therefore the previous assertion that it needs to know where to run is not true (except for that implementation detail) but its purpose is rather to get details about the interpreter. Other tools like Hatch and Poetry use a script that returns the [environment](https://peps.python.org/pep-0508/#environment-markers) of a given interpreter:

- Hatch: https://github.com/pypa/hatch/blob/hatch-v1.9.3/src/hatch/utils/env.py#L45-L79
- Poetry: https://github.com/python-poetry/poetry/blob/1.7.1/src/poetry/utils/env/script_strings.py#L30-L98

**Comment by hauntsaninja** [comment]
Sorry, I'm still a little bit confused about what your ask is. Note that `uv` does invoke the interpreter it is trying to install into in all cases:
- https://github.com/astral-sh/uv/blob/2586f655bbf650a9797c8f88b6d9066eefe7a3dc/crates/uv-interpreter/src/get_interpreter_info.py#L1
- https://github.com/astral-sh/uv/blob/2586f655bbf650a9797c8f88b6d9066eefe7a3dc/crates/uv-interpreter/src/virtual_env.rs#L31

I don't know if uv handles installing into base python on Windows correctly with the `VIRTUAL_ENV` trick (and that's more a question for #1374), but in the official docker image case you talk about uv does the right thing with the trick: `docker run --rm python:3.12 bash -c 'pip install uv mypy; VIRTUAL_ENV=$(python -c "import sys; print(sys.prefix)") uv pip freeze' `

**Comment by ofek** [comment]
- My point is that if we are provided an option for an explicit path then it would be far more rational for that option to be a Python binary which is ultimately invoked rather than a directory that must have a specific structure in order to find the aforementioned binary. The example I gave was a real one in which IDEs act upon paths to interpreters rather than directories per se.

    I didn't know UV already polls the interpreter; that's good! So it looks like just an oversight to be able to control the specific Python interpreter.
- What I was trying to show earlier was that the `VIRTUAL_ENV` environment variable is working by happenstance because the default [`sys.prefix`](https://docs.python.org/3/library/sys.html#sys.prefix) directory `/usr/local` happens to have a `bin` directory which matches the expected Linux virtual environment structure. As you mentioned this doesn't work on Windows and I'm not certain that works for all Linux installations either.

**Comment by hauntsaninja** [comment]
Okay, I think I see! To summarise:

- Currently, you can do `VIRTUAL_ENV=/path/to/prefix uv pip ...`
- It would be nice if you could instead do `uv pip --prefix /path/to/prefix ...`
  - This would make uv install into a specified virtual environment just a tiny bit nicer, which was my use case when opening this issue.
  - Honestly, I don't even mind the env var that much, I think I just ran `uv pip install --help` and didn't see the pip option that I knew I could use to do this. My intention here waas basically just a discoverability nit :-)
- Alternatively, the flag could be `uv pip --python-executable /path/to/python ...`
- `--python-executable` might have an advantage if you wanted this flag to be able to install into base environments, because while uv knows directory structure for venvs, it may not for base environments (see also #1374 / #1526 ). In particular, for base environment on Windows and for Linux distro provided Python (like when python is `/usr/bin/python3` and dist-packages nonsense is happening or whatever)

So I guess if I were uv, I'd figure out what/how I want to do 1374 / 1526 and maybe that determines what should happen here. Most of the demand in that issue is probably stuff like "make official python docker image work" or "make homebrew python work", for which logic equivalent to `VIRTUAL_ENV=$(python -c "import sys; print(sys.prefix)")` works fine. I spent some time looking at distro specific sysconfig stuff or macOS framework builds and frankly supporting those base environments looks horrible and maybe should be out of scope.

**Comment by wpk-nist-gov** [comment]
A solution to this would solve an edge case I'm running into.    I often have a conda environment with nox that then creates virtualenvs.  This leads to both `CONDA_PREFIX` and `VIRTUAL_ENV` variables being set.  With pip, this is easy to work around using `path/to/python -m pip` to install packages in the correct environment.  But having a flag like `--python-executable` or `--prefix` would also solve this.   This would hopefully help wntrblm/nox#762 as well.

**Comment by charliermarsh** [comment]
I’m planning to work on this next week. I’ll post here with a concrete proposal once I’ve had time to internalize the comments. (Probably something like a `--python` flag alongside a `--system` flag but TBD.)

**Comment by charliermarsh** [comment]
As far as I can tell from reading the linked Poetry source, apart from adding the arguments to the CLI etc., the main thing that would need to change to support arbitrary Pythons (outside of a virtual environment) is that we'd need to call `sysconfig.get_paths()` to get the various environment paths, rather than constructing them ourselves -- since the exact structure can vary for non-virtualenvs. Is there any reason this _wouldn't_ work?

**Comment by charliermarsh** [comment]
Definitely some things to learn from in the Poetry source: https://github.com/python-poetry/poetry/commit/e8f259a1f341f3f12ebc4822154bbea928ea323c

**Comment by fruch** [comment]
sharing one use case of using `--prefix` and `--root`, 

inside a multi stages docker build, one stage is building/collecting all packages and install them into a /build directory
and other stages just copy the content out of into their /usr/local folder.

meanwhile I've worked around using those pip flags, by VIRTUAL_ENV=/user/local, and copy all of /user/local between the layers.

**Comment by RonNabuurs** [comment]
> sharing one use case of using `--prefix` and `--root`,
> 
> inside a multi stages docker build, one stage is building/collecting all packages and install them into a /build directory and other stages just copy the content out of into their /usr/local folder.
> 
> meanwhile I've worked around using those pip flags, by VIRTUAL_ENV=/user/local, and copy all of /user/local between the layers.

This is the exact use case I also have

**Comment by fruch** [comment]
@charliermarsh I don't think the --python solved the equivalent `pip install --root` case, you want us to open a new issue for that ?

**Comment by strickvl** [comment]
@fruch there's also now a new `--system` flag which handles what you need, I think.

**Comment by Ox0400** [comment]
```
uv pip install --system uv 
```

**Comment by Andrej730** [comment]
Came to this looking for `--project` support for `uv pip`, which is documented as not supported by `uv pip`.
`--python` works really well for this, though it's a bit more verbose, since required interpreter path instead of just project dir.

<img width="797" height="304" alt="Image" src="https://github.com/user-attachments/assets/6c56685e-e9b6-4b95-aae5-792418790f9c" />
