### ISSUE TITLE
Support .netrc files

### ISSUE THREAD

**Issue by janbernloehr** [astral-sh/uv#1405]
pip supports obtaining credentials for authentication from `.netrc` files. This allows to keep `pip.conf`, `--index-url` and `--find-links` free of credentials and instead store them in a central place in `~/.netrc`.

Unfortunately, uv does not support obtaining credentials from there.

This is also required, for e.g. using requirements.txt files that refer to wheels at urls that require auth
```
torch @ https://foo.org/torch.whl
```

**Comment by zanieb** [comment]
Thanks for the report! We definitely need to address registry authentication.

**Comment by ejovo13** [comment]
Hello! How would a new contributor go about implementing this?

Pop open a new crate, something like `uv-credentials`, and then start cranking out code? I've got a fork compiled locally and I've poked around the codebase but I'm still very new to _collaborative_ software development. 

I guess my question is more general: How does one learn the inner machinations of a new project in order to make a useful contribution?

**Comment by brandon-piner-aruba** [comment]
We would also like the .netrc support. We specify the private repo in a slightly different way 

```
# From Gemfury (https://pypi.fury.io/the-org/)
# =============================================
some-package
```

**Comment by framillien** [comment]
Since you are using `reqwest` crate, using `reqwest-netrc` middleware could be an option ?

**Comment by framillien** [comment]
This work for index access, but fail on download since reqwest middleware is not used: 
https://github.com/astral-sh/uv/blob/main/crates/uv-client/src/registry_client.rs#L415

**Comment by framillien** [comment]
In fact this is not download in itself that cause this issue, but only the `read_metadata_range_request` usage. If I activate `reqwest-netrc` and skip all metada range errors [(here)](https://github.com/astral-sh/uv/blob/main/crates/uv-client/src/registry_client.rs#L457) the download succeed.

In my situation, the error we need to skip is an HTTP 401.
