### ISSUE TITLE
uv pip install fails with comparator on wildcard version specifier

### ISSUE THREAD

**Issue by fennovj** [astral-sh/uv#1477]
Minimal example:

requirements.txt with content:

```
requests>=2.30.*
```
or
```
requests<=2.30.*
```

`pip install -r requirements.txt` will succeed, but `uv pip install -r requirements.txt` will fail.

```
error: Couldn't parse requirement in `requirements.txt` at position 0
  Caused by: Operator >= cannot be used with a wildcard version specifier
requests>=2.30.*
        ^^^^^^^^
```

For an example in the wild (how I encountered this issue):

`pip install polars==0.14.0` succeeds, but `uv pip install polars==0.14.0` fails with

```
error: Failed to read metadata for: polars==0.14.0
  Caused by: Failed to parse METADATA file at: /Users/fenno/scratch/.env/lib/python3.10/site-packages/polars-0.14.0.dist-info/METADATA
  Caused by: Operator >= cannot be used with a wildcard version specifier
pyarrow>=4.0.*; extra == 'pyarrow'
       ^^^^^^^
```

**Comment by charliermarsh** [comment]
Thanks! That's actually not a "valid" specifier, but we have some fixups in the code for packages that use invalid specifiers. Will make sure this is covered.

**Comment by webcoderz** [comment]
still running into this problem

`37.90 stderr: error: Failed to download: torchsde==0.2.5
37.90   Caused by: Couldn't parse metadata of torchsde-0.2.5-py3-none-any.whl from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl.metadata
37.90   Caused by: Operator >= cannot be used with a wildcard version specifier
37.90 numpy (>=1.19.*) ; python_version >= "3.7"
37.90        ^^^^^^^^`

**Comment by charliermarsh** [comment]
Can you open a new issue please?
