### ISSUE TITLE
activate.nu error

### ISSUE THREAD

**Issue by Arengard** [astral-sh/uv#1490]
Scripts\activate.nu:95:1]
 95 │ export alias pydoc = python -m pydoc
 96 │ export alias deactivate = overlay hide activate
    ·                           ───┬───
    ·                              ╰── not allowed in pipeline
    ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.

**Comment by AucaCoyan** [comment]
Mmm this is a `virtualenv` issue, which is caused by upstream `nushell` shell script.
to better readability, I copy and paste in a monospaced font
```bash
  × Statement used in pipeline.
    ╭─[C:\Users\aucac\repos\exp-python\uv\.venv\Scripts\activate.nu:95:1]
 95 │ export alias pydoc = python -m pydoc
 96 │ export alias deactivate = overlay hide activate
    ·                           ───┬───
    ·                              ╰── not allowed in pipeline
    ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
  ```
  
  I could track this issue [firstly in `virtualenv`](https://github.com/pypa/virtualenv/issues?q=is%3Aissue+activate.nu) and then [in the issues of nushell/nushell](https://github.com/nushell/nushell/issues?q=is%3Aissue+%27overlay%27+keyword+is+not+allowed+in+pipeline.+Use+%27overlay%27+by+itself%2C+outside+of+a+pipeline.)
  
 I think is solvable, but it has nothing to do with `uv`

**Comment by AucaCoyan** [comment]
Hi! I'm using uv and venv in nushell. Do you keep getting issues @Arengard ?
