### ISSUE TITLE
Report uv version in pyvenv.cfg

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#1697]
Since virutalenv 20, it's included a `virtualenv=` field in `pyvenv.cfg` to indicate the version of virtualenv that created the venv. It would be nice to provide a similar `uv=` (suggested) field to report the version of uv used to create the virtualenv. This would also help nox detect which tool created the virtual environment to handle switching more elegantly.

There is a `gourgeist` field, don't know what that is, but if I can be sure that always means `uv`, that would be fine (though knowing the uv version would still be nice). Though from some quick searches, perhaps it would only be there [on UNIX systems](https://github.com/astral-sh/uv/blob/b76efc62a72ed8031aa91ae80bb1b4a159bd3d21/crates/gourgeist/README.md?plain=1#L5)?

**Comment by zanieb** [comment]
`gourgeist` is the crate by @konstin that actually manages virtual environments. It'd make sense to have it accept a name / version to pass through though and use `uv`.

**Comment by henryiii** [comment]
Does it live in this repo? Or is it copied from somewhere else?

**Comment by charliermarsh** [comment]
It lives in this repo.

**Comment by charliermarsh** [comment]
(To avoid confusion: there's a version at https://github.com/konstin/gourgeist but we ended up moving all the crates into this repo so that we could develop them as a monorepo. We'll likely either deprecate https://github.com/konstin/gourgeist and publish from here in the future, or back changes from this repo back out to https://github.com/konstin/gourgeist. But all development should happen on the version of `gourgeist` in `crates`.)
