### ISSUE TITLE
Add support for pinning a package to a specific index

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#171]
Discussed this with Armin -- pip doesn't support it, and it seems like a big problem? If you have an internal index, but also want to get some packages from PyPI, there's no way to ensure that your internal packages come from your internal index. Packages on PyPI could even shadow them.

**Comment by groodt** [comment]
Please consider dependency confusion attacks: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

Use of `--extra-index-url` as they are presently used are a security vulnerability. 

[PEP 708](https://peps.python.org/pep-0708/) is a yet-to-be-implemented approach to improving the security posture.

**Comment by charliermarsh** [comment]
I would love to implement improvements to this (like the ability to pin a dependency to a specific index)… We specifically held off and implemented indexes as-is to be spec-compliant. I’ll implement this as soon as it’s supported and there’s clarity on how installers should handle it!

**Comment by groodt** [comment]
Makes sense. 

I think you may receive a lot of duplicate feature requests from the folks who do misuse `--extra-index-url` and who aren't aware that it is not currently intended to be used to append additional sources of dependencies, it's purpose is to provide a set of fallback mirrors of the primary index (`--index-url`) which is PyPI in the general case.

We may need to consider offering some help as mentioned in the PEP to move this along.

In the short-term, if you don't want to bug-for-bug implement pip, we may need to point people at alternatives like https://github.com/uranusjr/simpleindex to help them merge indexes behind the scenes on localhost. I don't think many will like it 😂

**Comment by pawamoy** [comment]
@groodt can you point at official docs that confirm this use of extra index is indeed misuse? To me it fits well with local versions for example?

In any case, thanks for the links to simple index, this will be useful if case you're right and UV does not allow this use of extra index :) A bit sad to have to run two local servers instead of one, but that's not that bad.

**Comment by pfmoore** [comment]
> I don't quite understand why this is so hard

From what I recall (I quickly refreshed my memory on the issue but didn’t review the details) it’s a “design decision that was made a long time ago” type of complexity. Pip has built a bunch of choices on top of the “all indexes are equal and get merged” model, and it’s hard to know what we’d need to change if we were to revisit that decision. Add to that the need for backward compatibility and it’s a much bigger question than people saying “just pick the index I ask for” will accept.

For uv, I foresee the following issues:

1. Compatibility - you’ll diverge from pip in both subtle and not-so-subtle ways. This isn’t a bad thing, but your stated intention is to be compatible with pip, so you need to make choices here.
2. Being an outlier - the “all indexes are equal” model is not just something pip does. Standards like PEP 708 are built on the idea, so you may have trouble fitting that standard into your implementation. More generally, you’ll have to make a bunch of UI and design issues where there is less pre-existing experience to draw on.
3. Scope creep - people start wanting things like index priorities (“get these from piwheels when you can, but fall back to PyPI if there’s nothing at all published on piwheels”) which have their own issues.
4. You open yourself up to the idea that a package is no longer identified by just name and version - where it came from becomes important as well. This may have wider implications - for example, SBOM data might need extra information like source URL.

On the plus side, you’ll be offering a solution to something users have been wanting for a *long* time, and which is often characterised as a security issue. And practicality may well beat purity here.

>  can you point at official docs that confirm this use of extra index is indeed misuse

It doesn’t describe it as “misuse”, but the pip docs are clear that we treat all indexes as equal: “There is no ordering in the locations that are searched” from [here](https://pip.pypa.io/en/stable/cli/pip_install/). We (pip) could add a guide-type article discussing this in more depth, but we don’t have one currently.

**Comment by groodt** [comment]
There’s a small security warning in the pip docs [here](https://pip.pypa.io/en/stable/cli/pip_install/#examples)

`
Using this option to search for packages which are not in the main repository (such as private packages) is unsafe, per a security vulnerability called [dependency confusion](https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/): an attacker can claim the package on the public repository in a way that will ensure it gets chosen over the private package.
`

There is also an in progress pip PR to make this more explicit here https://github.com/pypa/pip/issues/11694

Here’s a major recent dependent confusion attack that impacted PyTorch (caused by instructions to use —extra-index-url) https://news.ycombinator.com/item?id=34202662

**Comment by pawamoy** [comment]
I'm not sure this is to answer my previous question ("can you point at official docs that confirm this use of extra index is indeed misuse"), but I was especially referring to "it's purpose is to provide a set of fallback mirrors of the primary index".

I distinguish two use-cases for extra indexes:

1. extend main index with additional projects (subject to dependency confusion)
2. extend specific projects in main index with additional versions (not subject to dependency confusion)

My understanding of your "append additional sources of dependencies" was that it referred to case 2, but now I think you were speaking of case 1.

So, to rephrase, and given pip currently considers all indexes to be equal, is case 2 is a misuse too?

**Comment by pfmoore** [comment]
Stepping back from the question of "why is this so hard", @groodt is correct that PEP 708 is the better solution here. Otherwise, does the user need to specify an explicit index for the whole of their internal package's dependency tree? What if someone adds a new internal module, and forgets to add it to the list of "must come from the internal index" list in all of their install jobs? Are we going to consider that as "user error"? The torchtriton attack took exactly this form. Or an attacker could compromise a *public* dependency of your internal project.

Having an index pin option doesn't prevent you from needing to handle the consequences of a "all distributions with the same name and version are interchangeable" model. It just gives users a manual way of firefighting issues with that model.

**Comment by pfmoore** [comment]
> So, to rephrase, and given pip currently considers all indexes to be equal, is case 2 is a misuse too?

It's not that "pip considers all indexes to be equal" but rather that "pip considers all distributions with the same name and version to be interchangeable *regardless of which index they came from*". The difference is subtle but important. Whether case 2 is a problem depends on whether you trust the "main index", just the same as with case 1. The trust issue is what's important here rather than what is "considered equal"[^1].

The `--extra-index-url` argument for pip was added long ago, in simpler times when people weren't anywhere near as worried about attackers targetting PyPI, and nobody was running multinational businesses based on Python code. Trust was generally assumed to be present, and in particular no-one was worrying about *relative* trust between indexes. Things have changed, for better or worse, and `--extra-index-url` doesn't match the new reality. This is why one of the options pip is considering is simply *removing* it, and demanding that users pick a single index and ensure that they trust that one index. That's unlikely to ever happen because the breakage would be significant, but it's absolutely an option that a new project like `uv` could (and should) consider.

To answer your question more explicitly, your case (2) is a "misuse" in the sense that it has risks (the same as case 1). The risks may not be a dependency confusion attack, but they do include compromise of the PyPI account owning of the code you're extending. Is that a more acceptable risk? Only you can decide that.

The point is that *mixing indexes with different trust levels*[^2] is the problem here. Even the "mirror PyPI" case involves a risk if the mirror is compromised.

[^1]: You could argue that if you don't trust two indexes equally, you don't "consider them equal", I guess...
[^2]: Within the same install command, which is why pinning for a set of named packages isn't a sufficient solution.

**Comment by pawamoy** [comment]
Thanks @pfmoore!

(Side note: I just discovered that PDM supports respecting the order of indexes: https://pdm-project.org/latest/usage/config/#respect-the-order-of-the-sources.)

**Comment by pfmoore** [comment]
Just as an example (and yes, it's a pathological case) if you have ordering, suppose you have index1 and index2 (ordered with 1 having priority over 2). Index 1 contains A 1.0 and B 1.0, with A 1.0 depending on B. Index 2 has B 2.0. If you install A, do you get B 1.0 or B 2.0? If the answer is 1.0, why did you bother specifying index 2? If you get B 2.0, and someone now adds A 2.0 to index 2, and changes B 2.0 to depend on A > 1.0, is the correct thing to upgrade A to 2.0, or downgrade B to 1.0?

The point here is that there's multiple possible choices, and if you don't factor index priority into the core of your resolution algorithm, you end up with a system that users won't have a good intuition about, and which might depend on implementation details. Both of which can lead to security issues. I'm not saying that PDM has such a problem - they may well have considered all of this. Just that "which index did this come from" is an extra axis you have to consider as part of resolution, *not* just something you can keep separate from the resolver.

Anyway, the key point for `uv`, and in answer to the question @charliermarsh asked above, is that *this* is why pip is still trying to work out a good answer to how we could allow users to choose which index to use at a more fine grained level than "per install".

**Comment by pfmoore** [comment]
> In my case, all packages from index 1 take precedence, even if higher versions are available in index 2.

Cool, so your approach to priority is like pinning, but with the decision on whether to pin being "if package A is in index 1, then pin to index 1, else fall through". That works, but it doesn't support the piwheels case where they *supplement* PyPI with wheels for the raspberry pi architecture, letting installers fall back to PyPI if the wheel isn't valid for the user's architecture (at least that's how I understand what they do...)

Getting into this much detail may be more than the `uv` maintainers want, though. Let's see if this is useful to them. I don't want to come across as saying that this is too hard to do - it's too hard for *pip* to easily do (which is what triggered my original comment) but `uv` may well have different priorities and choose different trade-offs. They also don't have backward compatibility to deal with (unless they want to match pip feature for feature).

**Comment by BurntSushi** [comment]
@pfmoore Thank you very much for your detailed comments here. They've been _super_ helpful.

I'd like to make a small tweak to how `uv` behaves today that will hopefully resolve at least some of the issues users are hitting (#1377, #1600, #1451) in practice, but do it in a way that doesn't make `uv` behave like `pip` (which, AIUI, is to consider all available packages from all indexes, without any guaranteed priority order).

So today, our implementation works by giving a preference order to the indexes made available to `uv`:

https://github.com/astral-sh/uv/blob/995fba8fec6ac6569e5f7ffe8d244faddef98692/crates/uv-client/src/registry_client.rs#L191-L210

That is, given `uv pip install --index-url foo --extra-index-url bar --extra-index-url quux package`, it will first try `foo`, then `bar` and then `quux`. Once a package is found, `uv` will stop looking for it in any other indexes. So for example, if `package` is found in `bar`, then that means it definitely wasn't found in `foo`, and it may or may not be in `quux`. We never check.

Since `--index-url` defaults to PyPI, that means something like `uv pip install --extra-index-url bar package` will check PyPI first for `package`, and if it's found, stop. I think this turns out to be the reverse of what the commonly desired behavior is. And while it won't address every use case, I think a nice stop-gap solution here would be to flip the preference order with respect to `--index-url` and `--extra-index-url`. That is, we check PyPI after all other extra index URLs given.

This will not match pip's behavior in every case, but I think it does help address some of the common cases and I think also helps to mitigate the dependency confusion concerns. That is, if `package` is in `bar`, then `uv` would completely ignore any packages named `bar` on PyPI. (Today, that's flipped. If `package` is on PyPI, then it will completely ignore any `package` on `bar`.)

Otherwise, I do agree that if we can get away with it, we should probably avoid encoding `pip`'s behavior of including packages from all indexes without regard to priority into `uv`. But we can certainly revisit this if my tweak above doesn't pan out.

And popping up a level, I do think we'll want to absolutely address the multi-registry issue by giving users more control when we build out more project management features. But I think until then, we'll probably want to avoid adding too many additional abstractions into `uv pip install` for dealing with multiple registries. And of course, I suspect we will want PEP 708 support eventually too.

**Comment by pawamoy** [comment]
Nice! Worth noting is users who want the flipped behavior can do `uv pip install --index-url https://private-index.com/simple --extra-index-url https://pypi.org/simple`, right?

**Comment by BurntSushi** [comment]
> Nice! Worth noting is users who want the flipped behavior can do `uv pip install --index-url https://private-index.com/simple --extra-index-url https://pypi.org/simple`, right?

Ah yes! I meant to call that out, but yes indeed.

**Comment by BurntSushi** [comment]
> ... while a proper solution would be enforcing association between specific packages and registries.

I think this is roughly what I meant above with:

> And popping up a level, I do think we'll want to absolutely address the multi-registry issue by giving users more control when we build out more project management features.

**Comment by atti92** [comment]
I have a similar problem. 
- Lets say you have a PKG with 1 yanked version available in UV_INDEX_URL or pypi.org
- You have the same package in your UV_EXTRA_INDEX_URL, but with valid versions.

1. when PKG is a dependency of something that we try to install, it works with latest uv version. :ok: 
2. trying to install the PKG, gives an error: :no_entry: 
```
error: Missing `Content-Type` header for <EXTRA_INDEX_URL>/PKG
```

- When you have multiple indexes in UV_EXTRA_INDEX_URL and the PKG is in the first extra:
1) same behaviour as with just 1 extra  :no_entry: 
- When the PKG is not in the first extra, but in subsequent extra indexes:
1) installation is not possible, it only looks for the package in the UV_INDEX_URL  :no_entry: 
```
× No solution found when resolving dependencies:
  ╰─▶ Because only PKG==0.0.0a1 is available and PKG==0.0.0a1 is unusable because it was yanked (reason: not stable), we can conclude that all versions of PKG cannot be used.
      And because you require PKG, we can conclude that the requirements are unsatisfiable.

      hint: PKG was requested with a pre-release marker (e.g., any of:
          PKG<0.0.0a1
          PKG>0.0.0a1
      ), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

**Comment by charliermarsh** [comment]
What's the case in which you're seeing `error: Missing `Content-Type` header for <EXTRA_INDEX_URL>/PKG`? That seems like a bug in the registry, but perhaps we can handle it gracefully.

**Comment by atti92** [comment]
> What's the case in which you're seeing `error: Missing `Content-Type` header for <EXTRA_INDEX_URL>/PKG`? That seems like a bug in the registry, but perhaps we can handle it gracefully.

- UV_INDEX_URL is undefined.
- UV_EXTRA_INDEX_URL points to a NEXUS instance with pypi repo

It only happens if I try to install a package that is available in both pypi.org and in the nexus.
Installing packages that are only in the nexus or pypi works.

**Comment by charliermarsh** [comment]
I think you want https://github.com/astral-sh/uv/issues/1754.

**Comment by atti92** [comment]
Yes I can confirm using `--no-cache` removes the error message.

Do you know anything about using multiple extra-index-urls, is that supposed to work?
it only resolved the package if it was in the first one, tried --extra-index-url and env too.

**Comment by atti92** [comment]
> > Do you know anything about using multiple extra-index-urls, is that supposed to work?
> > it only resolved the package if it was in the first one, tried --extra-index-url and env too.
> 
> See #2083

My package is only available in one of the extra-index-urls outside of index-url, but it still cannot find it, if it's not the first.

**Comment by BurntSushi** [comment]
> > > Do you know anything about using multiple extra-index-urls, is that supposed to work?
> > > it only resolved the package if it was in the first one, tried --extra-index-url and env too.
> > 
> > 
> > See #2083
> 
> My package is only available in one of the extra-index-urls outside of index-url, but it still cannot find it, if it's not the first.

It might be worth opening a new issue with a repro.

**Comment by atti92** [comment]
It seems like gitlab is doing an automatic pypi lookup:
https://docs.gitlab.com/ee/user/packages/pypi_repository/#install-a-pypi-package
```
In [GitLab 14.2 and later](https://gitlab.com/gitlab-org/gitlab/-/issues/233413), when a PyPI package is not found in the package registry, the request is forwarded to [pypi.org](https://pypi.org/).
```
Probably that's why it finds the yanked version again and stops looking at the subsequent extra-index-urls

**Comment by charliermarsh** [comment]
The next version of uv will include an opt-in flag to allow users to search for packages across multiple indexes. This is less secure, but closer to pip's behavior.

https://github.com/astral-sh/uv/pull/2815

**Comment by corleyma** [comment]
@smphhh me too, and I've used poetry plugin to accomplish something similar.  I know it's funky but it's a big 80/20 for corporate usecases.  It solves the problem of "if I pin a dependency to an index, from which index do I get the transitive dependencies?" for a narrow but useful set of cases.

**Comment by zanieb** [comment]
Removing with `wish` label here, as we expect to implement this in `tool.uv.sources`

**Comment by colinjc** [comment]
Current uv docs for dependencies make it sound like this feature is already available. Let to a bit of churn trying to figure out how to use it 😅 

https://docs.astral.sh/uv/concepts/dependencies/


> tool.uv.sources enriches the dependency metadata with additional sources, incorporated during development. A dependency source can be a Git repository, a URL, a local path, or an **alternative registry**.

**Comment by msabramo** [comment]
Does uv not expand environment variables in the `extra-index-url` setting in `pyproject.toml`? I couldn't get this to work:

```toml
[tool.uv]
# uv doesn't expand ARTIFACTORY_USER and ARTIFACTORY_API_TOKEN?
extra-index-url = ["https://${ARTIFACTORY_USER}:${ARTIFACTORY_API_TOKEN}@pythonpackages.corp.example.com/artifactory/api/pypi/pypi-colorado-tools-snapshot/simple"]
```

Great work on uv!

**Comment by zanieb** [comment]
Please comment on https://github.com/astral-sh/uv/issues/5734 regarding environment variable expansion.

**Comment by charliermarsh** [comment]
This is starting to come together in https://github.com/astral-sh/uv/pull/7481.

**Comment by samypr100** [comment]
> Poetry's design is interesting: https://python-poetry.org/docs/repositories/. It feels a bit more complex than is necessary though.

Here's an interesting pattern w/ poetry I've seen used to allow local dev on osx with pytorch but also enable GPU usage on linux.

```
[tool.poetry.dependencies]
...
torch = [
    ...
    { markers = "sys_platform == 'darwin' and platform_machine == 'arm64'", url = "https://download.pytorch.org/whl/cpu"},
    { markers = "sys_platform == 'linux' and platform_machine == 'aarch64'", url = "https://download.pytorch.org/whl/cpu"}
    { markers = "sys_platform == 'linux' and platform_machine == 'x86_64'", url = "https://download.pytorch.org/whl/cu121"}
]

**Comment by groodt** [comment]
Good news! 🎉

[Initial PEP 708 support has arrived on pypi](https://discuss.python.org/t/pep-708-extending-the-repository-api-to-mitigate-dependency-confusion-attacks/24179/94)

**Comment by k0t3n** [comment]
What about CLI? Will uv support adding dependencies with custom registries via `uv add`?

**Comment by gazpachoking** [comment]
> What about CLI? Will uv support adding dependencies with custom registries via `uv add`?

It looks like #7747 sorta does that. It doesn't allow just giving the index name though, you have to give the name and url. `uv add --index internal=https://internalindex.url somepackage` Allowing just using an existing index name would be a nice improvement.

**Comment by matteius** [comment]
fwiw, this is something pipenv actually does right -- we patch pip to force index restricted packages.   I was exploring what a uv resolver backend for pipenv would look like tonight and ran across this closed issue.
