### ISSUE TITLE
`uv pip install` doesn't compile pyc

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#1788]
pip does this by default (you can opt out with `--no-compile`). Without this, you pay the cost on first import, which is undesirable in various situations. (Also a thing to make sure is apples to apples when benchmarking)

**Comment by konstin** [comment]
We can add a `--compile` flag like poetry has (https://python-poetry.org/docs/cli/#install at the bottom).

The original motivation for this was that with bytecode compiling enabled, the majority of installation time in my benchmarks was spent on compiling.

> Without this, you pay the cost on first import, which is undesirable in various situations.

Could you elaborate?

**Comment by AlexWaygood** [comment]
> > Without this, you pay the cost on first import, which is undesirable in various situations.
> 
> Could you elaborate?

Whenever you import a `.py` file in Python, if Python doesn't see an associated `.pyc` file for that `.py`, the first time it is imported by Python, it will compile the `.py` module into a `.pyc` file and save that onto the disk (in a `__pycache__` directory). That means that the first time you use that module, the import will be much slower than any subsequent times the module is used. This is especially undesirable for e.g. a CLI tool. It means the first time the CLI tool is used will be much slower than any subsequent usages of the CLI tool, since a significant amount of time in the first usage will be spent by Python compiling all the Python code into `.pyc` files. After the first usage, Python will just reuse the `.pyc` files from the `__pycache__` directory, so you "only pay the cost on the first import", as @hauntsaninja says.

If you're an author of a CLI tool, it's desirable for the installer to pre-compile the Python files into `.pyc` files as part of the installation process, so that performance of the CLI tool is consistent from the start

**Comment by hauntsaninja** [comment]
Yup, like Alex says, this is undesirable in any case you're sensitive to import latency at runtime.

Another example is if you run your installs when building a container, you will now pay the cost every single time you start a job with that container, instead of just once upfront. This is especially bad if you're running a relatively short lived process in that container.

I know it makes benchmarks look worse (although in that case you should be comparing to `pip --no-compile` as your baseline), but this is genuinely useful time that users will be paying either way! Feels like generally a good use of performance envelope. I do think uv would be able to compile faster than pip does, a) pip does not do any multiprocessing, b) you have the opportunity to do copy-on-write for pyc files as well.

**Comment by charliermarsh** [comment]
Makes sense!

**Comment by thundergolfer** [comment]
Will +1 @hauntsaninja's comments about added container startup latency. At [modal](https://modal.com) we've found that when poetry's `--compile` flag is not used at build-time the resulting lack of `.pyc` files can add multiple seconds of startup latency for large packages: https://github.com/modal-labs/modal-client/pull/1112.

**Comment by charliermarsh** [comment]
@konstin is on it.

**Comment by Gerardwx** [comment]
This is also important if preparing package for installation as root with read-only permissions for end users.
