### ISSUE TITLE
Accept poetry and pipenv lockfiles for installation

### ISSUE THREAD

**Issue by abondrn** [astral-sh/uv#1804]
When `uv pip install` is passed `poetry.lock` or `Pipfile.lock` (and any optional dependency groups, or extras) instead of `requirements.txt`, it could attempt to install these in the uv environment. I can only speak for myself when I say this will speed up adoption of uv in some contexts we are using it, such as executing local tests or Docker pipelines.

**Comment by zanieb** [comment]
Similar to our policy on reading [pip-configuration](https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#configuration-files-and-environment-variables), I don't think we can do this. I think the bullets there are a good summary of why.

**Comment by michaelmior** [comment]
It might not be perfect, but it would be really helpful to have at least an attempt to import from pipenv configuration. You can get close with `uv add -r <(pipenv requirements)` but then all package versions are pinned because `pipenv requirements` is based on the lock file. The other piece would be reading from the Pipfile to specify the dependencies.

**Comment by zanieb** [comment]
Related

- #6425 
- #6520
