### ISSUE TITLE
Unable to install `pynacl==1.4.0`

### ISSUE THREAD

**Issue by srxavi** [astral-sh/uv#1906]
When executing `uv pip install pynacl==1.4.0` i get the following ouptut:

```
Resolved 4 packages in 2.33s
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pynacl==1.4.0
  Caused by: Failed to build: pynacl==1.4.0
  Caused by: Invalid pyproject.toml
  Caused by: TOML parse error at line 3, column 12
  |
3 | requires = [
  |            ^^^^^^^^^^^^
Expected a valid marker name, found 'python_implementation'
cffi>=1.4.1; python_implementation != 'PyPy'
```

**Platform**: MacOS Sonoma 14.3.1 on M2 Pro
**Version**: 0.1.9

**Comment by charliermarsh** [comment]
@konstin - Do you have a reference that we can include for `python_implementation`?

**Comment by konstin** [comment]
There's two compatibility layers: The more popular one, https://peps.python.org/pep-0345/#environment-markers

This one comes from https://github.com/pypa/packaging/issues/72 / https://github.com/pypa/packaging/pull/73/files though, which is now just https://github.com/pypa/packaging/blob/7bcd6d8ec33f0a614f9d017d31be4b50ece1549a/src/packaging/_parser.py#L326-L330

As usual, i advocate for emitting a warning when install such as a package, so that this can be fixed upstream.
