### ISSUE TITLE
`ModuleNotFoundError` when using `uv pip install` in GitHub Actions

### ISSUE THREAD

**Issue by kevinhu** [astral-sh/uv#1953]
Hi there! I'm using uv in a GitHub action but ran into `ModuleNotFoundError` when importing `click` and `tqdm`.

I'm using the latest version of `uv`. When I use `uv pip install`, I get several import errors, but when I use vanilla `pip install`, the action runs without issue. An example run: https://github.com/kevinhu/uv-gh-action/actions/runs/8032491324/job/21941942800

Here is a minimal example that reproduces these errors on Python 3.9 through 3.12: https://github.com/kevinhu/uv-gh-action. I've set up two jobs, `uv` and `pip`, that differ only in their install command: `uv pip install ...` vs `pip install ...`

**Comment by samypr100** [comment]
As far as I'm aware the virtual environment won't remain activated across steps in GHA since the shell reloads per step. In your pip workflow you end up installing dependencies outside the virtualenv, hence why you can import them. uv defaults to installing them on the .venv which is why you see uv failing.

**Comment by kevinhu** [comment]
Thanks! I thought the PATH modification would work but I guess not.

**Comment by charliermarsh** [comment]
Thanks @samypr100!
