### ISSUE TITLE
Invalid wheel: pip OK but uv KO

### ISSUE THREAD

**Issue by AntoineD** [astral-sh/uv#2149]
Hello,

when trying to install the package `openturns`, which is installable with `pip`, I get the following error
```shell
❯ uv pip install openturns   
Resolved 3 packages in 351ms
error: Failed to install: openturns-1.22-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (openturns==1.22)
  Caused by: The wheel is invalid: Line 3 of the WHEEL file is invalid
```
This is the contents of `WHEEL`:
```shell
❯ cat openturns-1.22.dist-info/WHEEL
Wheel-Version: 1.0
Generator: custom
Root-Is-Purelib: false
Tag: 
Tag: -manylinux_2_17_x86_64
Tag: -manylinux2014_x86_64
```

Is this issue on `uv`'s side?

**Comment by pfmoore** [comment]
Pip doesn't check the `WHEEL` file as far as I'm aware, so it looks like `uv` is being more strict here. But line *three* (which is what the error points to) is `Root-Is-Purelib: false`, which is fine. The `Tag` lines, though, *are* invalid - an empty `Tag` isn't valid, and the other two tags seem incomplete (should be `cp312-cp312-manylinux2014_x86_64` and `cp312-cp312-manylinux_2_17_x86_64`).

**Comment by konstin** [comment]
Sorry that's just an off-by-one error separate from this issue, fixed in #2151.

**Comment by zanieb** [comment]
Is the alternative here that we ignore all invalid tag entries?

**Comment by pfmoore** [comment]
Pip just uses the tags from the wheel filename. The `WHEEL` file is[^1] simply duplicating that information, so we just don't bother reading it. If you're using what's in the `WHEEL` file rather than what's in the filename, then you're going to have to deal with the fact that there might be garbage in there that's never been noticed before, precisely because pip never cared and nobody else bothered validating the data.

[^1]: Or at least *should* be 🙁

**Comment by konstin** [comment]
Thanks for the context! I think we should only warn about invalid `WHEEL` files then.

**Comment by charliermarsh** [comment]
Yeah I don't think we _use_ the information, but we do seem to validate it. I actually don't think we even validate the tags, we just choke if the value is empty AFAICT.

**Comment by charliermarsh** [comment]
I'll fix this real quick.
