### ISSUE TITLE
`uv pip install` fails when using #egg reference 

### ISSUE THREAD

**Issue by mrmattwright** [astral-sh/uv#2602]
```
uv --version
uv 0.1.5
```

When pointing at a private Pypi server that has links to a git reference uv fails where pip does not.

This works:
```
pip install model-copilot-core==0.1.2 --extra-index-url https://ORG.github.io/pypi/
```

This fails:
```
uv pip install model-copilot-core==0.1.2 --extra-index-url https://ORG.github.io/pypi/ -v
```
with 

```
error: Received some unexpected HTML from https://ORG.github.io/pypi/model-copilot-core/
  Caused by: Unsupported hash algorithm (expected `sha256`) on: egg=model-copilot-core-0.1.1
```  

The reason I think for this is that uv is expecting there to be a hash (either md5 or sha256), and if there isn't that's a failure case, whereas pip handles this. 

The HTML fragment in question (from the Pypi server) is 
```
<div id="0.1.2" onclick="load_readme('0.1.2', scroll_to_div=true);">
   <a href="git+https://github.com/ORG/model-copilot-core@0.1.2#egg=model-copilot-core-0.1.2">
   0.1.2
</a>
```

I had a look into the code at  https://github.com/astral-sh/uv/blob/main/crates/uv-client/src/html.rs#L147 and I think there is an assumption here that `fragment` will be the hashtype and hash ie; `sha256=...`.

I'm not entirely sure what would need to change to support installing in the way pip does this.

As a side note what I am doing is trying to have a minimal private Pypi server which is hosted on GH Pages that points to binaries in a GH release. So if there is any advice on the format of the URL in question, I am in control of that and can change it. I'll put that in a comment on this issue to keep that seperate.

**Comment by hmc-cs-mdrissi** [comment]
https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#legacy-features

```
uv does not support features that are considered legacy or deprecated in pip. For example, uv does not support .egg-style distributions.
```

As a note pip also [plans](https://github.com/pypa/pip/issues/12330) to remove support for eggs too.

**Comment by charliermarsh** [comment]
We don't support eggs or `#egg` references. We should be able to install `git+https://github.com/ORG/model-copilot-core@0.1.2` though without the trailing fragment?

**Comment by fmagin** [comment]
I have stumbled on a case where I am actually required to add a `#egg` reference, otherwise a build fails:

This works and successfully installs all the packages based on the commit:
```
  uv pip install --prerelease=allow --no-build-isolation --upgrade \
   ailment@"git+https://github.com/angr/ailment.git@98dbad4285456f27a55198c227aedb14bcdf1007#egg=ailment"\
   archinfo@"git+https://github.com/angr/archinfo.git@ffe2770156c54856b40cee4ea810721910d861bb#egg=archinfo"\
   pyvex@"git+https://github.com/angr/pyvex.git@eb087cc88d0660c2fdb09edbb907e0bd66bbc6da#egg=pyvex"\
   claripy@"git+https://github.com/angr/claripy.git@75095fe46f1ab99fd3dc3670ee82ae13282b0166#egg=claripy"\
   cle@"git+https://github.com/angr/cle.git@c39f0a4c51c0e5cc32ad14e1497761fb00ad470a#egg=cle"\
   angr@"git+https://github.com/fmagin/angr.git@abf07e0d7b727296e134c29da6cb24a30e7b91cb#egg=angr"
```

This does not:
```
  uv pip install --prerelease=allow --no-build-isolation --upgrade \
   ailment@"git+https://github.com/angr/ailment.git@98dbad4285456f27a55198c227aedb14bcdf1007"\
   archinfo@"git+https://github.com/angr/archinfo.git@ffe2770156c54856b40cee4ea810721910d861bb"\
   pyvex@"git+https://github.com/angr/pyvex.git@eb087cc88d0660c2fdb09edbb907e0bd66bbc6da"\
   claripy@"git+https://github.com/angr/claripy.git@75095fe46f1ab99fd3dc3670ee82ae13282b0166"\
   cle@"git+https://github.com/angr/cle.git@c39f0a4c51c0e5cc32ad14e1497761fb00ad470a"\
   angr@"git+https://github.com/fmagin/angr.git@abf07e0d7b727296e134c29da6cb24a30e7b91cb"
```

and fails with:
```
Resolved 45 packages in 16ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: angr @ git+https://github.com/fmagin/angr.git@abf07e0d7b727296e134c29da6cb24a30e7b91cb
  Caused by: Failed to build: angr @ git+https://github.com/fmagin/angr.git@abf07e0d7b727296e134c29da6cb24a30e7b91cb
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
Building angr_native
--- stderr:
<string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
error: You must install pyvex before building angr
---
```

The specific source of this error is from the [`setup.py` of angr](https://github.com/angr/angr/blob/a895283f96fe1090a8c6415185a53170d9dd9c17/setup.py#L25-L29)

How does adding the `#egg` reference make a difference if you claim to not support it? It seems to cause some discernible difference during the install of packages.
uv version is 0.1.23

**Comment by charliermarsh** [comment]
I can take a look, although... In order for that build to work, you _need_ to install `pyvex` before `angr`, because you're running with `--no-build-isolation` and `angr` depends on `pyvex` as a build dependency. I don't know why it works in the first example, it shouldn't necessarily work in either case.

**Comment by mrmattwright-mt** [comment]
@charliermarsh thanks - not supporting `#egg` refs makes sense - I did not see that in the docs. 🙏 @hmc-cs-mdrissi 

if you remove the egg reference both pip and uv fail with similar messaging. 

```
ERROR: Could not find a version that satisfies the requirement model-copilot-core==0.1.2 (from versions: none)
ERROR: No matching distribution found for model-copilot-core==0.1.2
```

Which I think is because

> For sdists located via an index, the filename is parsed for the name and project version (this is in theory slightly less reliable than using the egg_info command, but avoids downloading and processing unnecessary numbers of files).
> 
> Any URL may use the #egg=name syntax (see [VCS Support](https://pip.pypa.io/en/stable/topics/vcs-support/)) to explicitly state the project name.

via https://pip.pypa.io/en/stable/cli/pip_install/#working-out-the-name-and-version 

but I will have a good read of the spec and report back. Another option would be to link directly to the `.zip` or `tar.gz` but GH release links for private repos redirect to a temporary link so you end up with a 404. 😞
