### ISSUE TITLE
pick some real Python projects and attempt to port them to `uv` with universal locking

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#3881]
I'd like to start small (as in, a small dependency tree) but with a project that benefits from having a platform independent lock file. So probably a project that utilizes the universal locking of Poetry or PDM.

I'd also like to try locking packse's `pyproject.toml` and see what happens.

The idea is to see what issues arise with our universal locking implementation in real projects.

Ref #3347

**Comment by adeebshihadeh** [comment]
We're excited to switch for [openpilot](https://github.com/commaai/).

Previous attempt here: https://github.com/commaai/openpilot/pull/32530.

**Comment by helderco** [comment]
Curious to try it in [dagger](https://github.com/dagger/dagger/tree/main/sdk/python) modules, but I'll need to catch up on these changes.

**Comment by jab** [comment]
[bidict](https://github.com/jab/bidict) has a pretty small dependency tree (no runtime deps, and just a [handful of test deps](https://github.com/jab/bidict/blob/main/dev-deps/test.in), in case it's a good candidate for testing this with. It currently uses `uv pip compile`-[generated](https://github.com/jab/bidict/blob/bf916bd/dev-deps/update_dev_dependencies#L48) requirements files (rather than Poetry or PDM). Looking forward to simplifying all those test.txt requirements files (under the [dev-deps/*](https://github.com/jab/bidict/tree/main/dev-deps) subtree) that have been required without this feature.

**Comment by zanieb** [comment]
I ported packse in https://github.com/astral-sh/packse/pull/183 if anyone is interested in what that looked like.
