### ISSUE TITLE
Different understanding of environment markers vs pip

### ISSUE THREAD

**Issue by wimglenn** [astral-sh/uv#3917]
Minimal reproducer:

```
$ cat pyproject.toml
[project]
name = "example"
version = "0.1"
dependencies = [
    "dep1; platform_release >= '1.0'",
    "dep2; platform_release < '1.0'",
]
```

uv pip wants to install dep1

```
$ uv pip install .
  × No solution found when resolving dependencies:
  ╰─▶ Because dep1 was not found in the package registry and example==0.1 depends on dep1, we can conclude that example==0.1 cannot be used.
      And because only example==0.1 is available and you require example, we can conclude that the requirements are unsatisfiable.
```

python pip doesn't want to install either

```
$ .venv/bin/pip install -q .
$ .venv/bin/pip list
Package Version
------- -------
example 0.1
pip     24.0
```

**Comment by charliermarsh** [comment]
Any idea which is correct?

**Comment by wimglenn** [comment]
Hmm, I'm not 100% sure if this is well-defined even by the standards. I don't see anything in [PEP508](https://peps.python.org/pep-0508/) explicitly describing the situation.

To reproduce it, `platform.release()` should be returning a string which can not be parsed as a valid version number. An example container which does that:

```
$ docker run --rm -it python:3.12.3-bookworm python -c 'import platform; print(platform.release())'
5.10.104-linuxkit
```

It is quite normal for this to be a string which is not parsable as a version number, PEP508 even offers such examples (`3.14.1-x86_64-linode39`, `14.5.0`, `1.8.0_51`). It means the marker can't be evaluated:

```
$ docker run --rm -it python:3.12.3-bookworm bash
root@60f3aae789ef:/# pip install --root-user-action=ignore -q packaging
root@60f3aae789ef:/# python3
Python 3.12.3 (main, May 14 2024, 05:40:55) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.requirements import Requirement
>>> req = Requirement("dep1; platform_release >= '1.0'")
>>> req.marker
<Marker('platform_release >= "1.0"')>
>>> req.marker.evaluate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/packaging/markers.py", line 252, in evaluate
    return _evaluate_markers(self._markers, current_environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/packaging/markers.py", line 158, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/packaging/markers.py", line 116, in _eval_op
    return spec.contains(lhs, prereleases=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/packaging/specifiers.py", line 558, in contains
    normalized_item = _coerce_version(item)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/packaging/specifiers.py", line 26, in _coerce_version
    version = Version(version)
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '5.10.104-linuxkit'
```

It would seem that pip considers this case by default as evaluating False. I'm not sure what uv is doing (string comparison lexicographically maybe?)

**Comment by konstin** [comment]
Using `platform_release` with greater/lower operators is unfortunately broken:

The paragraph you quoted from PEP 508 translates into a two-step procedure: Try to parse left hand side and right hand side as PEP 440 versions. If this succeeds, apply the operator as defined by PEP 440. If either side fails to parse, compare lexicographically. That means the behaviour of `platform_release < '1.0'` depends on whether `platform_release` of the host happens to be PEP 440 compatible or not, something that may even change between releases (e.g. with a pre- or post-release scheme that incompatible to PEP 440, while the regular version is compatible. The behaviour then silently switches between PEP 440 semantic comparisons and lexicographic comparisons, which can have the inverse result (e.g. `3.9` > `3.10` is false by PEP 440 but true by lexicographic order). We used to have warnings for this, but i think we turned them off because they were too noisy.

The pip behaviour you're observing is odd, i'd have to dig into the code again to see if that may have changed recently.

**Comment by charliermarsh** [comment]
Going to close for now based on the above -- thank you both!

**Comment by h4l** [comment]
@konstin @charliermarsh In case either of you are have an opinion or are interested, we're trying to get the Python implementation of PEP 508 environment marker evaluation to match the spec's behaviour. As noted here, the spec's behaviour currently uses lexicographic order to compare version strings that don't match spec's version grammar, which can produce incorrect/unintuitive results for system-provided version strings that aren't valid  python package versions.

There's some discussion on whether the spec should be updated to solve this problem, or whether the `packaging` package should just be patched to match the spec as-is. 

(Currently the `packaging` package (and tools that use it, like pip) are (unintentionally) failing with an error when evaluating expressions with version strings that don't match the spec's version grammar, instead of doing lexicographic comparison as the spec requires.)

See this comment from Brett Cannon on the `packaging` issue for this: https://github.com/pypa/packaging/issues/774#issuecomment-3120526922
And there's a thread about it on: https://discuss.python.org/t/reconciling-packaging-module-the-dependency-specifier-specs-non-version-to-version-comparison-rules/100287

**Comment by konstin** [comment]
I did some research into cases for published package metadata where the fallback to lexicographic would apply, and found only unintended behavior that worked more or less accidentally before Python 3.10 (since lexicographically, "3.10" is lower than "3.9" for the first time).

**Comment by h4l** [comment]
So if I understand correctly, for you the current lexicographic fallback is good enough in practice?

**Comment by konstin** [comment]
I think the lexicographic fallback only causes confusion, a marker should have a only a single mode in which it gets evaluated. `platform_release` and `platform_version` are confusing markers by design, as it's not clear if their contents will fit any specific format, so I advise users against using them, but I don't have a good suggestion how to deal with exiting usage.

**Comment by h4l** [comment]
I see, thank you.
