### ISSUE TITLE
Implement `uv add`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3959]
As part of the Project API, we should have native `add` and `remove` commands.

**Comment by ibraheemdev** [comment]
https://github.com/astral-sh/uv/pull/4193 provides the initial implementation. However, there are still some improvements and open questions:
- [ ] Accept unnamed URLs.
- [ ] Support dev dependencies with `--dev`.
- [ ] How should `uv add` interact with `tool.uv.sources`?
- [ ] Editable requirements?

**Comment by charliermarsh** [comment]
Also: adding dependencies that are extras.

**Comment by matterhorn103** [comment]
Excited for what's to come! Forgive my curiosity here. :) I almost asked this in #3560, where the differences and potential confusion between the planned commands `uv tool add` and `uv tool install` are discussed, but figured it's actually more relevant here.

Are you guys planning on a command that installs packages to the current venv (or system-wide, I guess) independent of a "project"-like setup? I.e. where there is no `pyproject.toml` present?

`uv pip install` is brilliant for standard package installation in this manner because of how fast it is, but your intention seems to be for the `uv pip` stuff to eventually only be a compatibility layer, rather than something that is regularly used.

But at the same time, if my impressions from your comments in various places are correct, a `uv install` command will be deliberately avoided?

Or will `uv add` work anyway without either needing a `pyproject.toml` or creating one?

**Comment by ibraheemdev** [comment]
Opened https://github.com/astral-sh/uv/issues/4419 and https://github.com/astral-sh/uv/issues/4418 to track the remaining tasks.

**Comment by ibraheemdev** [comment]
@matterhorn103 Yes, the new project APIs are structured specifically around `pyproject.toml` and `uv.lock`. The intention is you won't have to deal with lower level operations directly.
