### ISSUE TITLE
How to use different index url with `pyproject.toml` when using `uv pip compile`

### ISSUE THREAD

**Issue by SamComber** [astral-sh/uv#4173]
I'm trying to convert my Pipfile to a pyproject.toml, so that I can run:

`uv pip compile pyproject.toml --generate-hashes -o requirements-lock.txt`

The issue is I have a package, torch, that uses a different index in my Pipfile

```
[dev-packages]
torch = { index = "pytorch_cpu"}

[[source]]
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
name = "pytorch_cpu"
```

How can I reproduce what my Pipfile is achieving here, and specify a different index url to install `torch` here? Ideally I'd like to keep this all contained within `pyproject.toml` - is this possible?

P.S. loving the blazing speed of `uv`!

**Comment by charliermarsh** [comment]
You should be able to do:

```toml
[tool.uv.pip]
extra-index-url = ["https://download.pytorch.org/whl/cpu"]
```

...in your `pyproject.toml`. We don't support assigning a package to a specific index yet but it's on the roadmap.

**Comment by charliermarsh** [comment]
If you need Torch to be an optional dependency, we don't yet support development dependencies like that though it's coming soon (and already supported in `preview` mode but not everywhere you'd need it). So you would need to use extras, like:

```toml
[project.optional-dependencies]
dev = ["torch"]
```

And then `uv pip compile pyproject.toml --extra dev --generate-hashes -o requirements-lock.txt`.

**Comment by SamComber** [comment]
Success! Thank you @charliermarsh 

One last blocker if you would care to help me out

Would you know how to install your project in editable mode? Is this possible? 

```
[dev-packages]
my_project = {editable = true, path = "."}
```

I've been trying

```
[dev-packages]
"my_project@file:///Users/sam.comber/Documents/kraken/my_project"
```

`uv pip compile pyproject.toml --extra dev --generate-hashes -o requirements-lock.txt`

But I can't see the project as editable inside the `requirements-lock.txt?`

**Comment by patrick-kidger** [comment]
I can answer this one. The main limiting factors getting in the way of this is that (a) Python has no way to express editable dependencies in `pyproject.toml` files, and (b) the Python package format (wheel files) has no way to express editable dependencies either. That latter one means that you can't pass on transitive editable dependencies.

Fortunately, it's possible to work around this!

In your `pyproject.toml` file, first express all your dependencies as just file dependencies: `foo_lib @ file:////path/to/foo_lib`. Then run `uv pip compile`. This will do the right thing because `uv` will actually go back and recompute a file dependency if the target's `pyproject.toml` has been modified, so you'll pick up on any changes to transitive dependencies.

Now instead of running something like `uv pip sync requirements.txt`, replace it with something like `cat requirements.txt | sed <some regex magic> | uv pip sync -`. Just replace file dependencies with editable dependencies, which *are* expressible in either `requirements.txt` files or via stdin. This means you'll actually get an editable install of your target, and you'll pick up on any changes to the code itself.

(Footnote: the editable format you need to use is `-e file:///path/to/foo_lib`, note the lack of any `foo_lib @` at the start.)

**Comment by charliermarsh** [comment]
Thanks @patrick-kidger :)
