### ISSUE TITLE
Add `uv tool list`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4486]
Should list installed tools. See #3560

**Comment by caiquejjx** [comment]
Hey @zanieb I found `uv` today and would like to contribute, this looks like a good first start, is it free to grab? If so I'll work on it.

**Comment by zanieb** [comment]
Hey @caiquejjx — I've started on this over in #4630 but I appreciate the interest!

How much Rust experience do you have? Are you looking for a very straight-forward task or something a bit more involved?

**Comment by zanieb** [comment]
Also, in #4630 we note it'd be nice to include version numbers in the output of `uv tool list` and it'd be nice to display the installed entrypoints too if you're interested in exploring either of those.

**Comment by caiquejjx** [comment]
@zanieb I'm a starter in Rust and I've been trying to contribute to Rust projects to learn more + help projects I like. Since I don't have a lot of experience with Rust and I'm just getting to know uv I'm looking more for straightforward tasks to get acquainted with it and later possibly work on more elaborated tasks. Adding the version + entrypoint seems like a good one, I would like to work on it. Thanks!

**Comment by zanieb** [comment]
Sounds good! I've opened an issues for both of those. Let's chat over there.

- https://github.com/astral-sh/uv/issues/4653
- https://github.com/astral-sh/uv/issues/4654
