### ISSUE TITLE
Support `manylinux_x_y` in `--python-platform`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4966]
See: https://github.com/astral-sh/uv/pull/4965.

This is a bit tricky because we still want great output in the `--help` menu and JSON schema, but it will no longer be static and I don't think we can use `ValueEnum` or other derives.

**Comment by JonZeolla** [comment]
I think this was fixed per 7925d255f7de18cc0e658955a71f9f50bee6b32d ?

**Comment by charliermarsh** [comment]
That added support for `manylinux_2_31` but not arbitrary `manylinux_x_y`.

**Comment by filaretov** [comment]
Would you accept a PR that adds enumerations for the `manylinux` policies in [this table](https://github.com/mayeut/pep600_compliance?tab=readme-ov-file#acceptable-distros-to-build-wheels) just like what was done in #4965?

I understand it is not the general support for `manylinux_x_y` that this issue is about, but if you're okay with it, I'd be happy to make a PR.

**Comment by filaretov** [comment]
Here it is: #9234

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/9234.
