### ISSUE TITLE
`--resolution lowest` with `uv sync` needs to discard preferences

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5226]
Currently, when switching to `uv sync --resolution lowest` from `uv sync`, nothing changes, because we're using the existing preferences. This breaks the use case for `--resolution lowest`.

We should instead discard the preferences when using `--resolution lowest` or `--resolution lowest-direct`, since these two modes are not for regular development, but for testing your dependency specifiers.

**Comment by charliermarsh** [comment]
I don't consider this a bug, but we can consider changing it.

**Comment by charliermarsh** [comment]
I don't think discarding preferences alone would change this. We'd also have to skip the "resolve from lockfile" behavior.

**Comment by charliermarsh** [comment]
Perhaps we _always_ do both these things if `--resolution` is set explicitly...? Like, say that it implies `--upgrade`?

**Comment by charliermarsh** [comment]
I can try it.

**Comment by charliermarsh** [comment]
I guess arguably `--prerelease` and other settings should have the same effect, but I don't know where to draw the line.

**Comment by konstin** [comment]
Do we need to record the settings use for the resolution in `uv.lock`?

**Comment by charliermarsh** [comment]
The downside of that approach is that it wouldn't work for `uv pip install --resolution lowest`, which has also led to confusion before and would be nice to solve here.

**Comment by charliermarsh** [comment]
No obviously-good solution here... Options are something like:

- Use `--upgrade` semantics whenever `--resolution` is explicitly provided. But, how does this work when `--resolution` is provided via a configuration file? We never pin? That wouldn't work.
-  Write the `resolution` and `prerelease` to the lockfile, so that we can rerun when they're mismatched. This is good, but it doesn't solve the same problem that already exists for `uv pip install`, which has been described before: #1647.

I suspect we need to do the latter, though.

**Comment by charliermarsh** [comment]
We probably want to record the `resolution`, `prerelease`, and `exclude-newer` setting.

**Comment by charliermarsh** [comment]
Working on that change (adding resolution options to the lockfile).

**Comment by charliermarsh** [comment]
I wonder if, eventually, we'd want to enable projects to have multiple locks for this purpose. Or enable the lockfile to contain multiple entries if they resolve with different input settings.

**Comment by zanieb** [comment]
It seems like it depends on the use-case. Are you going to always run your project in `lowest` resolution because you prefer it? I don't know why you'd need multiple lock files in that case. Or is it a single invocation in CI to test if the lowest versions are correct? There, I don't think the lock matters at all?

**Comment by charliermarsh** [comment]
Are you commenting on the originating issue here or my previous comment?

**Comment by zanieb** [comment]
The previous comment.
