### ISSUE TITLE
`uvx` doesn't upgrade when existing tool is installed

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5797]
This is a confusing workflow:

```
❯ uv tool install ruff==0.0.60
Resolved 1 package in 5ms
Installed 1 package in 3ms
 + ruff==0.0.60
Installed 1 executable: ruff

❯ uvx ruff --version
ruff 0.0.60

❯ uvx --upgrade ruff --version
ruff 0.0.60
```

**Comment by charliermarsh** [comment]
Not 100% sure what the semantics should be here, it's actually pretty tricky. _Even if_ we respected `--upgrade` here properly, we wouldn't upgrade the installed tool past `0.0.60`, since the receipt has `ruff==0.0.60` in it. So, like, even if you did `uvx --upgrade ruff` and we gave you latest Ruff, running `uvx ruff` again would... give you `0.0.60`.

I wonder if we should avoid using installed tools _ever_ in `uvx` now that we have cached environments.

**Comment by charliermarsh** [comment]
\cc @zanieb

**Comment by zanieb** [comment]
I think using the installed tool wasn't intended as a performance thing, rather it's part of the experience to use the version you've chosen to install by default. This becomes more important when we consider project-level tools where `uvx` would invoke the project-specific version by default. We could reconsider that experience.

The `--isolated` flag was intended to ignore the installed version. Is there an equivalent for that now?

A `--latest` flag was discussed in the design, should we add that?

I don't think `--upgrade` is even intended to be available in `uvx` since it's an ephemeral environment? If resolver options are passed, we should probably just ignore the receipt entirely?

**Comment by charliermarsh** [comment]
Yeah `--isolated` already exists.

**Comment by charliermarsh** [comment]
I guess we can ignore the installed tool if you pass `--upgrade` or `--reinstall`?

**Comment by charliermarsh** [comment]
@zanieb -- I might expect `ruff@latest` to work
