### ISSUE TITLE
Check `{ workspace = true, editable = false }` support

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5958]
We need to check the support of non-editable workspace dependencies in `pyproject.toml`. If it doesn't work remove it from the docs.

See also #5792.

**Comment by charliermarsh** [comment]
I've confirmed that this isn't supported. The issue is that we have to lock the entire workspace. So we add all the members (as editable), then lock, then install the appropriate subset.

In order to support this, I think we'd need to make editable part of `dependencies`, rather than its own source... Since we'd need the workspace member to be a `directory` that can either be installed as editable or non-editable.

**Comment by charliermarsh** [comment]
Do we want to support or remove? \cc @zanieb

**Comment by zanieb** [comment]
I guess we should remove it for now.

**Comment by charliermarsh** [comment]
I think I should make a timeboxed effort to fix it.
