### ISSUE TITLE
`uv pip install --target` inconsistencies

### ISSUE THREAD

**Issue by schlamar** [astral-sh/uv#6198]
I use `pip install --target` to build compatible package directories for different platforms to distribute applications. For example

`pip install --platform=win_amd64 --target packages-win64 --only-binary=:all: --python-version 310 "sqlalchemy>=2,<3"` 
`pip install --platform=win32--target packages-win32 --only-binary=:all: --python-version 310 "sqlalchemy>=2,<3"`

There are inconsistencies using `uv pip install` compared to `pip`.

**1) It requires an active virtual environment**

```
> .\venv\Scripts\uv.exe pip install --target temp --only-binary=:all: --python-version 3.12 --python-platform windows sqlalchemy
error: No virtual environment found
```
When using `--target` an active virtual environment doesn't make sense for me.

**2) You cannot install binary packages with different architecture on Windows**

With pip I can install 32bit packages running a 64bit Python and vice versa. With `uv` I couldn't find a way to explicitly select 32bit packages. 

Running `uv install` with a 64bit Python I couldn't find a way to install 32bit packages (I guess that's a missing feature).

Running `uv install` with a 32bit Python and without `python-platform` installs 32bit packages. Running `uv install` with a 32bit Python and `--python-platform windows` installs 64bit packages. I would consider the latter behavior as a bug - that's really unexpected.

**3) Parameter `--implementation` missing in uv**

With `pip` you can use `--implementation py` to only select packages which don't have platform dependent binary content. I couldn't find a way to reproduce this behavior with `uv`. See https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/

**Comment by charliermarsh** [comment]
> When using --target an active virtual environment doesn't make sense for me.

You can pass `--system` to avoid requiring a virtual environment.

> Running uv install with a 32bit Python and without python-platform installs 32bit packages. Running uv install with a 32bit Python and --python-platform windows installs 64bit packages. I would consider the latter behavior as a bug - that's really unexpected.

We don't have a target triple for 32-bit Windows. We could add one. But the current behavior is intentional. If you pass `--python-platform`, we entirely ignore the Python platform of your current interpreter. And the docs mention that `windows` is an alias for `x86_64-pc-windows-msvc`. If we start mixing the current interpreter with the `--python-platform`, you lose all of the guarantees that `--python-platform` provides (i.e., that it's independent of the current platform).

**Comment by zanieb** [comment]
See https://github.com/astral-sh/uv/issues/5973 regarding the documentation — it's not announced/public yet but will be soon.

> So my expectation here is actually that ruff should detect automatically if it is installed in a virtual envrionment and use that.

If you want uv to do this, use `venv\Scripts\python -m uv` — it'll detect and use the parent interpreter's environment then.

> A common use case is to use pip from an virtual environment without having the virtual environment activated

If you don't want to activate the environment, but want uv to detect it, set `VIRTUAL_ENV` to the path.

> With pip you can use --implementation py to only select packages which don't have platform dependent binary content.

I'd presume we could add this without too much difficulty, but I'd prefer we discuss support for it it in a dedicated issue instead of lumping everything together.
