### ISSUE TITLE
uv cache prune --ci prunes everything in the cache

### ISSUE THREAD

**Issue by valentincalomme** [astral-sh/uv#6312]
I've just upgrade to `uv==0.3.0` and was happy to see a tip about caching in Github actions in the documentation.

Although, by applying what is described in the docs, and running `uv cache prune --ci`, my entire cache is pruned and I'm left with  a 240KB cache, which is far too small for the dependencies that I have.

Am I misunderstanding how this command should work?

**Comment by zanieb** [comment]
For some use cases, we will prune nearly the entire cache. The details are described [in the docs](https://docs.astral.sh/uv/concepts/cache/#caching-in-continuous-integration).

**Comment by charliermarsh** [comment]
Yeah, it's strange, but it turns out that it's actually (a lot) faster to just re-download from the registry than it is to upload and then re-download from GitHub Actions (which is roughly what happens when you cache the wheels that came from the registry). So counterintuitively, our `uv cache prune --ci`, removes any _wheels_ that were downloaded from a registry, but keeps any _source distributions_ that you built locally (since those tend to be costly).
