### ISSUE TITLE
Run `uv sync` without creating venv (similar to poetry config) (I believe `uv pip` has functionality like that)

### ISSUE THREAD

**Issue by adiberk** [astral-sh/uv#6459]
Our current Dockerfile install command with poetry - we can disable venv creation
`poetry config virtualenvs.create false...`

It would be nice to be able to run `uv sync` with a similar command `uv sync --no-venv` or something.  This way we don't have to change how our app is built and run, as well as commands that get run when exec into docker
As of now using a venv in our Dockerfile causes too much of a headache (at least from what i can tell)

**Comment by charliermarsh** [comment]
Not yet but we're likely to support it soon.

**Comment by leddy231** [comment]
We need this as well coming from a similar poetry setup.

But perhaps it should not be a functionallity of `uv sync`, as it is designed to work with virtual envs and add / remove packages to match the lockfiles.

Would it make more sense to allow `uv pip install` to be able to read `uv.lock` files? Then the command would be
`uv pip install -r uv.lock --system` 
With an optional `uv lock --locked` to make sure the lockfile is up to date.

This would also allow installing multiple projects in the same system python without it uninstalling previous packages (which im guessing `uv sync` would do?). This is also something we need, becuse we still have just a single dockerfile for our multiple projects :sweat_smile:

**Comment by leddy231** [comment]
> Sorry, but this is a use-case I don't think uv sync should support — if you need to install multiple projects side-by-side you need to use workspaces and a single lockfile otherwise you're throwing out all of the guarantees that the project interface is built on.

Yes thats what i meant, `uv sync` should not be able to do that, but raw `uv pip install` should (and yes it would not be good practice, but sometimes needed)

**Comment by xymz** [comment]
FYI, In some cases(especially on CI), I also need something like `uv sync --system` or `uv pip install -r pyproject.toml --system --with-dev`. There is a workaround for last one(https://stackoverflow.com/a/78902981) but I think it is not follow uv standard. And it is not cool add some extra dependencies for CI(of course, It is could be meaningful if there is a difference) because it's redundant.

Yes, it's clear that we need a consistent option for using uv without virtualenv in special cases. Or we'll always have to spend time finding workarounds for every edge case.

**Comment by zanieb** [comment]
This is supported by #6834 now

**Comment by xymz** [comment]
@zanieb Nice and cool. Thanks for your considerate working.

**Comment by dpnova** [comment]
A use case here is we're deploying to AWS lambda using their container feature. Installing things outside the system folder is a pain... 

I'm thinking `sync` is not for us and we should use export to get a requirements file to install.

**Comment by mc51** [comment]
> A use case here is we're deploying to AWS lambda using their container feature. Installing things outside the system folder is a pain...
> 
> I'm thinking `sync` is not for us and we should use export to get a requirements file to install.

@dpnova: I was (probably) trying to solve the same issue. Turns out, it's possible now using [this](https://github.com/astral-sh/uv/pull/6834) which was mentioned [above](https://github.com/astral-sh/uv/issues/6459#issuecomment-2330368355).

In the `Dockerfile` for the lambda deployment, I'm using `FROM public.ecr.aws/lambda/python:3.12`.
Now, we set `ENV UV_PROJECT_ENVIRONMENT="/var/lang/"`.  The system python binary is in `/var/lang/bin/` for this image. So, uv will operate on the system python. Following, we can use `uv sync` with our lock file to install dependencies to the system.   
However, because `uv sync` will also [delete dependencies from the system](https://github.com/astral-sh/uv/pull/6834#issue-2495678347) which aren't defined for our project, **one must be cautious**. For example, we'll need to make sure `awslambdaric` is added as a dependency, otherwise lambda will fail.

**Comment by dpnova** [comment]
Thanks @mc51 I suspect my attempts were removing deps as you say... Good info, cheers!
