### ISSUE TITLE
`uv init` should create a runnable project

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6471]
I got some feedback on Twitter that it'd be nice if `uv init` created something that you could then `uv run` and immediately see feedback, similar to how `cargo new` gives you a "Hello, world!" application. You shouldn't need to figure out how to change the project to make it runnable, etc.

**Comment by charliermarsh** [comment]
(Open to feedback, an idea.)

**Comment by zanieb** [comment]
Yes please! I wanted this but didn't want to require it for `uv init` to start.

**Comment by hauntsaninja** [comment]
This is the perfect opportunity to unleash the puffin:
```
print(r"""
         .-"-.
        /  _uv\_     .---------------.
        \  \__))}> _/  Hello, World!  \
        ,) ." \    \__________________/
       /  (    \
     ,"   )    ;
     )   /     /
   ,/_."`  _.-`
    /_/`"\\___
         `~~~`
""")

```

**Comment by charliermarsh** [comment]
This is actually not bad...

**Comment by zanieb** [comment]
Wow!

**Comment by suomela** [comment]
I think ideally this would be fully compatible with uv's "tools", so that e.g. this works directly without any extra hassle:

- On one computer, I run `uv init foo`, and upload the newly created repository "foo" somewhere on Github (without any manual edits).
- On another computer I run `uv tool install git+https...`, and I have got my newly created command-line tool "foo" installed there, and it directly works: I can run `foo` and it prints out "Hello world!" or something.
- And now naturally I can add further functionality, push to Github, and run `uv tool upgrade` everywhere to get the latest features.

This would give a really low-threshold approach for everyone (including very beginners) to develop their custom command-line tools and install them conveniently on their own computers.

**Comment by epequeno** [comment]
I agree that being able to run the project directly after `init` would be a useful feature but in the meantime this is what I'm doing.

`rye` supported `project.scripts` which allowed you to create an alias or command to run your project: https://rye.astral.sh/guide/pyproject/#projectscripts

I might be mistaken but I didn't see anywhere in the `uv` documentation that this feature/config was supported but it seems that it is.

So, after you `init` a project you can add a section to the `pyproject.toml` to create a convenient run command:

```
~ $ mkdir foo
~ $ cd foo/
~/foo $ uv init
Initialized project `foo`
~/foo $ echo -e "\n[project.scripts]\nmain = 'foo:hello'" >> pyproject.toml
~/foo $ uv sync
~/foo $ uv run main
Hello from foo!
```

I'd love to hear if there's a better way to approach this but this works for me.

**Comment by suomela** [comment]
Interesting, I didn't realize setting up `[project.scripts]` is enough; I thought I'd have to add `print()` or something in the `hello()` function for it to actually print something.
