### ISSUE TITLE
Wrong Python path reported in uv python list

### ISSUE THREAD

**Issue by adaamz** [astral-sh/uv#6515]
Hi,
I think I misunderstand `uv python list` command or it returns something I wouldn't expect 🤔 

```dockerfile
FROM python:3.9.19-slim-bookworm
RUN python3 -m venv /opt/venv
RUN uv pip install ruff
```
This fails on `error: No virtual environment found`
but when I add `/opt/venv` to `$PATH`
```dockerfile
FROM python:3.9.19-slim-bookworm
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN uv pip install ruff
```
then this passes and it is OK I guess.
But the small issue is that `uv python list --only-installed` reports the same thing in both cases (with and without `$PATH` replaced)

from the Docker container:
```
root@7d4f7b1a5615:/# echo $PATH
/usr/local/bin/
root@7d4f7b1a5615:/# uv python list --only-installed
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python3.9
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python3 -> python3.9
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python -> python3

root@7d4f7b1a5615:/# export PATH=/opt/venv/bin:$PATH
root@7d4f7b1a5615:/# echo $PATH
/opt/venv/bin:/usr/local/bin/
root@7d4f7b1a5615:/# uv python list --only-installed
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python3.9
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python3 -> python3.9
cpython-3.9.19-linux-x86_64-gnu    usr/local/bin/python -> python3
```
I would expect `/opt/venv/bin/python3` here... or do I miss/understand something?

`which` returns `/opt/venv/bin/python3` correctly
```
root@7d4f7b1a5615:/# /usr/bin/which python3
/opt/venv/bin/python3
root@7d4f7b1a5615:/# /usr/bin/which python3.9
/opt/venv/bin/python3.9
```

uv 0.3.2

**Comment by zanieb** [comment]
Hi! We exclude virtual environments from `uv python list` https://github.com/astral-sh/uv/blob/04e3e7ce65b9ea1b5f42442e8f2f47ca8e80d445/crates/uv/src/commands/python/list.rs#L74

We can document this. Is the a particular reason you want or need to see it there?

**Comment by konstin** [comment]
`uv pip install` by default recognizes virtual environments called `.venv`. For other names, you need to either activate the virtual environment, or pass it with `-p /opt/venv/bin/python`.

We don't recommend adding virtual environment pythons to `PATH`, this can lead to confusing behavior. I think `uv python list` does not show it since it's not a system interpreter, but a effectively a link to a system interpreter.

Since you are in docker, you may be interested in the `--system` flag that tells `uv pip` to install into the global python installation of the docker container instead of a virtual environment. (Which is fine to do in docker, unlike on your host system where there may be other projects and system dependencies, too)

**Comment by zanieb** [comment]
I think we should add support for showing the interpreter that we'll use in `uv python find` (which ignores virtual environment interpreters as well, right now).

**Comment by konstin** [comment]
Sorry, `VIRTUAL_ENV` and `PATH` is correct as activation in docker (it's emulating what `. .venv/bin/activate` does), i got confused because the `VIRTUAL_ENV` part was missing.

**Comment by zanieb** [comment]
Adding support for this in https://github.com/astral-sh/uv/pull/6521
