### ISSUE TITLE
Feature Request: `uv tool install/uninstall/upgrade` supports multiple packages

### ISSUE THREAD

**Issue by pplmx** [astral-sh/uv#6571]
As title

**Comment by zanieb** [comment]
And what do you expect to happen if you do `uv tool install --with foo black httpx`?

**Comment by pplmx** [comment]
Why not run `uv tool install ruff commitizen pre-commit`? I hope these three can be installed.

**Comment by zanieb** [comment]
Sorry that's not answering my question — what do you expect ot happen when you use `--with` or other flags with multiple install targets?

**Comment by pplmx** [comment]
It seems that `--with` is intended for managing executables that require additional dependencies, whereas the aforementioned feature request focuses on installing, upgrading, or uninstalling multiple independent executables at the same time

**Comment by zanieb** [comment]
So the problem here is `uv tool install tool1 tool2` is fine but once other flags are included, e.g., `--with plugin1` it doesn't make sense if `plugin1` should be applied to both tools or what. We're not excited about complicating the install interface to support multiple packages in this way.

However, I think `uv tool uninstall` and `uv tool upgrade` could definitely support multiple names.
