### ISSUE TITLE
Pin Python version on `uv init`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6821]
See #6780 

Might want https://github.com/astral-sh/uv/issues/4970 first, but I don't think it's blocking.

Basically, we should pin the Python version for the project on init. We should allow opt-out with `--no-pin-python`.

**Comment by charliermarsh** [comment]
For app and lib?

**Comment by zanieb** [comment]
I think so — either way you want to develop on a consistent version.

**Comment by samypr100** [comment]
In the spirit of this comment https://github.com/astral-sh/uv/issues/6780#issuecomment-2316388155, wouldn't we want to opt-in with `--pin-python` instead of opting out? Even on `app` mode I typically see just minimum major.minor on the requires-python metadata field where as `.python-version` does contain a pinned version.
