### ISSUE TITLE
Document/explain what the "hatchling" build-system is about

### ISSUE THREAD

**Issue by gdamjan** [astral-sh/uv#7132]
`uv init` adds the hatchling build system to pyproject.toml.

please write a short blurb (a sentence or two) what that means, and why it is needed.

(I personally have no idea what the role of `hatchling` is in the whole `uv` concept)

**Comment by zanieb** [comment]
We don't do this by default anymore, but hatchling is a build backend which is required to build and install your project: https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend

We choose hatchling because we think it's a reasonable option, but there are many other backends. Eventually, we'll write our own #3957.

Learn more about build-systems and uv projects at https://docs.astral.sh/uv/concepts/projects/#build-systems
