### ISSUE TITLE
Pylyzer not working with uv

### ISSUE THREAD

**Issue by daltunay** [astral-sh/uv#7204]
uv version `uv 0.4.7 (a178051e8 2024-09-07)`

---

I want to use [pylyzer](https://github.com/mtshiba/pylyzer) but it does not seem to work when using uv.

```
$ pip install pylyzer
$ pylyzer main.py
<PYLYZER OUTPUT>
```
-> WORKING

```
$ uv add pylyzer
$ uv run pylyzer main.py
Start checking: broker.py
<HANGS HERE>
```
-> NOT WORKING

```
$ uv pip install pylyzer
$ uv run pylyzer main.py
Start checking: broker.py
<HANGS HERE>
```
-> NOT WORKING

---

Thanks in advance for helping

**Comment by smheidrich** [comment]
I can't reproduce this on my machine (Debian 12, amd64):

If I just install Pylyzer by itself with either `pip` or `uv` and run it on a file, it prints errors like `[ERR] ERG_PATH not found`  (but still seems to check files fine?) until I also install `erg` manually using `cargo install erg`, which populates a `~/.erg` directory, after which these errors disappear. I never get the freezing issue you report.

Maybe it's worth reporting this on the pylyzer side as well because their devs probably know more about how their [setup script](https://github.com/mtshiba/pylyzer/blob/56e016e9159207519767d331e4a4f34eaa1c181b/setup.py) works and what the issue could be.

**Comment by charliermarsh** [comment]
I also can't reproduce this:

```
❯ uv run pylyzer ../main.py
[ERR] ERG_PATH not found
[ERR] ERG_PATH not found
[ERR] ERG_PATH/lib/pystd not found
[ERR] ERG_PATH not found
[ERR] ERG_PATH/lib/core.d not found
Start checking: main.py
All checks OK: main.py
```
