### ISSUE TITLE
Completion should fall back to default shell completion behavior when input does not match  

### ISSUE THREAD

**Issue by dandavison** [astral-sh/uv#7401]
I'm using zsh. Given a file `./hello.py`, I think that e.g. `uv run python he<TAB>` should complete to `uv run python hello.py` (assuming that no other paths match `./he*`). I.e., I think that `uv`'s completion should fall back to some appropriate "normal shell completion" behavior when the input cannot be completed in a uv-specific way.

**Comment by shirayu** [comment]
I have noticed the same problem.
I have't coded Rust at all, but I did a little looking into it.

It looks like adding ``#[clap(value_hint(ValueHint::AnyPath))]`` to the following is needed, but that is not possible due to `#[command(subcommand)] ` .
https://github.com/astral-sh/uv/blob/2ed94745a2cba996c617ffbb686a2d99baf7fecc/crates/uv-cli/src/lib.rs#L2659-L2664

**Comment by zanieb** [comment]
Is this the same as https://github.com/astral-sh/uv/issues/8432 ?

**Comment by shirayu** [comment]
@zanieb  I think so, thank you.

**Comment by zanieb** [comment]
Please let us know if this is broken outside of Zsh

**Comment by hmrc87** [comment]
I have the same problem but it works in bash (on Mac OS) but not on zsh (MacOs)

**Comment by dandavison** [comment]
Sorry I forgot to say when I opened the issue, yes I'm using zsh (I don't use oh-my-zsh). I agree this is a duplicate of #8432 (could remove oh-my-zsh from that title). Since GH lets me do so, I'll go ahead and close as a dup.

**Comment by phaabe** [comment]
> Please let us know if this is broken outside of Zsh

@zanieb 
yes it does also break on ghostty

https://github.com/astral-sh/uv/issues/8432#issuecomment-2567865617
