### ISSUE TITLE
Support uv tool reinstall

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#7471]
When upgrading Python interpreters, it would be beneficial to allow upgrading all tools to a different Python. Something like:

```
uv tool reinstall --python 3.13
```

**Comment by zanieb** [comment]
Related to https://github.com/astral-sh/uv/issues/7320

I'm a bit hesitant to add a `reinstall` command. I wonder if we could cover this in `uv tool upgrade`?

**Comment by gaborbernat** [comment]
It would be an option:

`uv tool upgrade --python 3.13` could also work 👍

**Comment by tfsingh** [comment]
Working on this, have an initial (rough draft) [here](https://github.com/astral-sh/uv/compare/main...tfsingh:uv:tfsingh/tool-upgrade-python?expand=1)!

Still needs formal testing (but seems to be working after installing a tool with --python 3.12, upgrading with --python 3.13, and verifying the change in uv/tools/tool's pyvenv.cfg)

**Comment by daviewales** [comment]
In the PR above, @tfsingh notes:

> Upgrading with --python also upgrades the package itself

This makes sense for the `upgrade` command, as it is normally used to upgrade the version of packages.

However, I think this suggests that a `reinstall` command may still be needed, because it would allow changing the Python version, while keeping all other options unchanged.

See the pipx [reinstall](https://pipx.pypa.io/stable/docs/#pipx-reinstall) and [reinstall-all](https://pipx.pypa.io/stable/docs/#pipx-reinstall-all) commands.
