### ISSUE TITLE
AGPL License file in Source Distributes Confused License Scanners ...

### ISSUE THREAD

**Issue by rlgloden** [astral-sh/uv#7566]
Sorry to bother for such a stupid problem but corporate scanners are flagging the AGPL license in the uv-0.4.13\ecosystem\pretix\license file in the uv source code zip ... which we have to scan before using the executable ... even if we use pip to install it.

I can't tell if pretix package is currently even used in tests yet but its existence in the source code zip is causing issues convincing our decision makers that uv isn't really AGPL and the pretix is only being used for test purposes.

**Comment by charliermarsh** [comment]
We can just remove it. I'll replace it with something that isn't AGPL.

**Comment by charliermarsh** [comment]
(It's just an example project that we resolve during the test suite.)

**Comment by rlgloden** [comment]
Again ... sorry for such a silly bother!!!

**Comment by musicinmybrain** [comment]
This was actually really helpful for me in the Fedora package, as `pretix` has additional custom/nonstandard terms (“exceptions”) on top of the AGPL. Even though plain `AGPL-3.0-only` code is acceptable in Fedora, I was having to use a modified source archive with the contents of `ecosystem/pretix/` removed while waiting for legal review of pretix’s idiosyncratic extra terms. Since `saleor` is just `BSD-3-Clause`, I can now go back to distributing the unmodified `uv` source archives in the source RPMs.
