### ISSUE TITLE
uv add jax  ,    all  jax code indent are     in  disorder  

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#7580]
![图片](https://github.com/user-attachments/assets/43878069-fc07-45e7-88c2-c2e18fde3d5b)

# indent error 

![图片](https://github.com/user-attachments/assets/b9aa8d41-3dc5-4ef6-97f7-8aa1f9f4cd02)

win 11  
uv latest version

**Comment by Super1Windcloud** [comment]
just   uv   add  jax , you can try   out to do

**Comment by Super1Windcloud** [comment]
uv  pip install jax    as  well

**Comment by notatallshaw** [comment]
JAX uses 2 space intending:

 * https://github.com/jax-ml/jax/blob/jaxlib-v0.4.32/jax/_src/tree_util.py#L332
 * https://github.com/jax-ml/jax/blob/jaxlib-v0.4.32/pyproject.toml#L112

The fact that your IDE is warning about that (probably because there is a user setting to 4 spaces) is unrelated to the traceback you are getting. If you care about the IDE warning you should seek out support for that IDE.

If you think the exception you are getting is related to uv, you need to provide steps on how you got to that exception for someone to be able to help you.
