### ISSUE TITLE
[question] When I used uv to install `ddddocr===1.4.11`, the installed dependent version was not quite correct 

### ISSUE THREAD

**Issue by gcil125** [astral-sh/uv#7588]
- command : `uv pip install ddddocr==1.4.11 -v` 
- platform : `Darwin(macos14)` 
- uv version ：`uv 0.4.12 (2545bca69 2024-09-18)`

I installed `ddddocr====1.4.11` using uv,  and the dependent numpy version installed was 2.1.1. However, when I installed ddddocr using pipenv, the dependent numpy version installed was 1.26.4 

Why is this? Can it be avoided?

<img width="962" alt="image" src="https://github.com/user-attachments/assets/c809f6c5-a96b-4ae9-80d8-b019b15444a8">

**Comment by charliermarsh** [comment]
`ddddocr==1.4.11` declares a dependency on `numpy` without any version constraint. So we'll attempt to use the latest version of NumPy, which is 2.1.1. (That's correct and expected behavior.)

If you want to get a different version of NumPy, I'd suggest either `uv pip install ddddocr==1.4.11 numpy==1.26.4`, or create a `constraints.txt` file with:

```
numpy==1.26.4
```

And then run `uv pip install ddddocr==1.4.11 -c constraints.txt`.

**Comment by zanieb** [comment]
Some more details on the basics of resolution at https://docs.astral.sh/uv/concepts/resolution/#basic-examples — which includes an example of how resolvers can find different but equally valid resolutions.

**Comment by gcil125** [comment]
When uv installs a package, will it compile the package again on my computer? Can I install the package that has been released on pypi without compiling it?

**Comment by charliermarsh** [comment]
Yes, it the author of the package published a compiled version that is compatible with your computer’s architecture, operating system, and Python version.

**Comment by zanieb** [comment]
You can also use `--no-build` to request that we do not compile packages, but then we'll fail if they have not published one for your platform.
