### ISSUE TITLE
How to use config files for tools?

### ISSUE THREAD

**Issue by andreas-vester** [astral-sh/uv#7732]
When using tools like ``ruff``, ``mypy``, ``pytest`` etc., I am using config files, such as ``ruff.toml`` or dedicated sections in ``pyproject.toml`` file.

If installing these tools via ``uv tool install``, where am I supposed to put the respective configurations?

Also, I need to make sure that all team members do have the same settings, which is probably not as easy as putting them into a concrete project repo, isn't it?

**Comment by charliermarsh** [comment]
It depends on the tool. Ruff, for example, supports user-level configuration: https://docs.astral.sh/ruff/faq/#how-can-i-change-ruffs-default-configuration. So you'd put it at `~/.config/ruff/ruff.toml`. Or, you can put a `ruff.toml` at the root of each project (or anywhere on the filesystem really) and Ruff will discover it when checking those files.

MyPy almost always needs to be installed into the virtual environment that it's type-checking, so it generally doesn't make sense to install as a tool.

(I'm not certain on how `pytest` configuration works, but again, it probably makes sense for that to be a project dev dependency rather than a tool.)

**Comment by asmaier** [comment]
For people who end up here I want to give an example. If you want to configure `ruff` you can just add some dedicated sections `[tool.ruff*]` to your `pyproject.toml` created by `uv` like so

```
[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anonymous", email = "anonymous@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "F"]
```

Then you can just run `ruff`

    uv run ruff check

and it will pick up your configuration from the `pyproject.toml`.

See also
- https://docs.astral.sh/ruff/configuration/
