### ISSUE TITLE
Feature: Provide a Debian package

### ISSUE THREAD

**Issue by jondo** [astral-sh/uv#8047]
I am on Linux Mint, and I would like to start using uv, but I have been taught not to trust arbitrary installer scripts like your https://astral.sh/uv/install.sh . Also, I would like to avoid `pip install uv`, since I cannot be sure this keeps my local Python environment stable.

So I would like to humbly ask for a Debian uv package.

(This might only make sense at a 1.0 release. Is there a road map for 1.0? According to [this closed milestone](https://github.com/astral-sh/uv/milestone/1), uv is already feature complete.)

(Update: I have now used pipx for installing uv.)

**Comment by zanieb** [comment]
I don't think we can maintain this — someone from the Debian package repository would need to.

**Comment by jondo** [comment]
That's a pity.

Hmm, I can only use pip within a virtualenv, otherwise I get `error: externally-managed-environment` (even with `pip install --user uv`). However I have the feeling that I should be able to use uv _instead of_ virtualenv (+piptools), not in _addition_ to it.

**Comment by konstin** [comment]
By default, uv doesn't install pip into the virtualenv. You can use `uv pip` or alternatively create the venv with pip by using `uv venv --seed`.

**Comment by jondo** [comment]
@konstin , sorry, I think you misunderstood. My comment was about how to use pip in a venv to install uv, not about how to use uv to create a venv with pip.

**Comment by konstin** [comment]
I'm not sure why `pip install --user uv` is failing, that is not something we control.

To come back to the original post:

> but I have been taught not to trust arbitrary installer scripts like your [astral.sh/uv/install.sh](https://astral.sh/uv/install.sh)

If you are looking for a download without running a script, you can get an archive from https://github.com/astral-sh/uv/releases/latest. You can also download and inspect the installer script before running it.

**Comment by zanieb** [comment]
More details on all that in https://docs.astral.sh/uv/getting-started/installation/

I think there's also a snap available for uv on Debian. I wouldn't recommend snap personally, but it might be what you want.

**Comment by mescanne** [comment]
Comment on this -

I recommend using pipx. It is distributed with debian (apt-get install pipx) and allows you to install arbitrary pip-delivered CLI tools. So pipx install uv will put uv in $HOME/.local/bin.

The benefit is that you can upgrade (pipx upgrade uv) when and how you'd like to the latest, without being constrainted by Debian's release cycle.

**Comment by pszpetkowski** [comment]
> I recommend using pipx. It is distributed with debian (apt-get install pipx) and allows you to install arbitrary pip-delivered CLI tools. So pipx install uv will put uv in $HOME/.local/bin.

That's exactly been my setup for the past few months and it works fine, however uv aspires to cover pipx features: 

> A single tool to replace pip, pip-tools, **pipx**, poetry, pyenv, twine, virtualenv, and more.

Providing Debian package right now would not benefit the users so much, since it's actively developed and releases are very frequent, but imo it should be considered after uv reaches some level of maturity (e.g. after 1.0 release).

**Comment by zanieb** [comment]
I don't think this is in scope for us, happy to support a Debian package maintainer if anything is needed — just reach out.

**Comment by collinanderson** [comment]
FYI: Here is the tracking bug on the debian side of things. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069776

Sounds like as of Dec 1st, most of the rust dependencies were either not packaged or out of date. https://lists.debian.org/debian-python/2024/12/msg00000.html

Also, a possible issue I see with packaging uv, is that as far as I understand, the `uv python list` is [hardcoded](https://github.com/astral-sh/uv/blob/main/crates/uv-python/download-metadata.json), so a packaged/frozen version of uv will never be able to install python bugfixes or security fixes, unless someone regularly backports the python list, rebuilds, and republishes.

**Comment by linsomniac** [comment]
I'm doing a preview of a github action to build deb package, currently only for x64 Linux.  You can use this repo by doing:

```
sudo wget -O /usr/share/keyrings/uvrepo.gpg https://linsomniac.github.io/uvrepo/pubkey.gpg
sudo chmod 644 /usr/share/keyrings/uvrepo.gpg
echo "deb [signed-by=/usr/share/keyrings/uvrepo.gpg] https://linsomniac.github.io/uvrepo nobel main" | sudo tee /etc/apt/sources.list.d/uvrepo.list
apt update
apt install uv
```

Please provide feedback on the linsomniac/uvrepo github repo.

**Comment by zanieb** [comment]
> Sounds like as of Dec 1st, most of the rust dependencies were either not packaged or out of date. https://lists.debian.org/debian-python/2024/12/msg00000.html

We're pretty on top of using the latest versions of packages. If things aren't packaged, it's usually because we're on the bleeding edge of what's available. Other downstream maintainers have opened issues tracking / requesting switching to a packaged distribution — feel free to do so for any blocking dependencies.

> Also, a possible issue I see with packaging uv, is that as far as I understand, the uv python list is [hardcoded](https://github.com/astral-sh/uv/blob/main/crates/uv-python/download-metadata.json), so a packaged/frozen version of uv will never be able to install python bugfixes or security fixes, unless someone regularly backports the python list, rebuilds, and republishes.

This is only the case for versions managed by uv — we support using system versions. We'll explore supporting dynamic loading of new managed Python versions eventually, but it will require stricter versioning of the distributions from `python-build-standalone`, i.e., if the distributions change there an old version of uv will not know how to install it.

**Comment by linsomniac** [comment]
Note: My longer term plan, once I have feedback on it, would be to submit the uvrepo work as a PR to uv, so that astral can directly publish an apt repo of their artifacts alongside the direct downloads of tar files.  Assuming Astral is interested, but I can't imagine why not.  Until then my repo is building daily off the latest available uv release.

**Comment by linsomniac** [comment]
FYI: I've added i386, s390, and aarch64 to the repo.

**Comment by ianbmacdonald** [comment]
Glad to see the packages are underway;  My production best practices, which I try to adhere to in the homelab, also include avoid pip natively, install scripts of any kind, and to a lesser extent snap. @linsomniac thanks, daily package builds will suit my needs just fine, and apt preferences can be used for reproducable production builds to move uv further into the stack.  I note, to help AI bots landing here for installation instructions, that you are using /usr/share/keyrings rather than /etc/apt/keyrings .. the former is for keyrings managed by a Debian package .. the later is for the [operator managed ones](https://forum.collaboraonline.com/t/dont-use-usr-share-keyrings-for-pgp-keys-which-are-not-managed-by-a-package/3786).

**Comment by ianbmacdonald** [comment]
Guess I got ahead of myself;  https://linsomniac.github.io/uvrepo/ is 404.  Guess there was a bit more to it ;)

**Comment by ianbmacdonald** [comment]
This looks like a good option for Debian based platforms. 

https://dario.griffo.io/posts/how-to-install-uv-debian/
https://github.com/dariogriffo/uv-debian

**Comment by dariogriffo** [comment]
Yup, that's me, updates are pushed the same day.
Added support to more architectures 3 weeks ago.
I'll also add in the near future instructions to ensure package signatures are only valid with my key pair.


> This looks like a good option for Debian based platforms.
> 
> https://dario.griffo.io/posts/how-to-install-uv-debian/ https://github.com/dariogriffo/uv-debian

**Comment by esennesh** [comment]
> Yup, that's me, updates are pushed the same day. Added support to more architectures 3 weeks ago. I'll also add in the near future instructions to ensure package signatures are only valid with my key pair.
> 
> > This looks like a good option for Debian based platforms.
> > https://dario.griffo.io/posts/how-to-install-uv-debian/ https://github.com/dariogriffo/uv-debian

I get an error when trying it about its not being secure:

> Error: The repository 'https://debian.griffo.io/apt questing Release' does not have a Release file.
> Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
> Notice: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by dariogriffo** [comment]
@esennesh Just added ubuntu now, questing will be available from next uv release, so keep an eye!
