### ISSUE TITLE
Question:  Difference between workspaces and editable-dependencies

### ISSUE THREAD

**Issue by xiaoxiangmoe** [astral-sh/uv#8195]
What's the difference between [workspaces](https://docs.astral.sh/uv/concepts/workspaces) and [editable-dependencies](https://docs.astral.sh/uv/concepts/dependencies/#editable-dependencies)? It seems that they all can make we add dir `packages/bird-feeder` as package `bird-feeder`.

Should all workspaces be editable-dependencies?

**Comment by konstin** [comment]
Editables are an older, standardized mechanism. They are a You could use them in `requirements.txt` to emulate workspaces, e.g.:

```
-e .
-e packages/bird-feeder
```

Editables don't say anything about the relationship these packages have to each other, they just a path dependency that says that a certain package should be built and installed in editable mode instead of in regular mode.

Workspaces are a uv feature that allows managing multiple packages in a single repository together. It does more than editables (or path dependencies in general), such as sharing a lockfile and sources. By default, all members of the workspace are installed as editables.

**Comment by charliermarsh** [comment]
A workspace member is a package within a workspace. A package can be installed as editable or non-editable. By default, we install all workspace members in "editable mode", but you can pass `--no-editable` to disable that.
