### ISSUE TITLE
Convention on pip installing uv

### ISSUE THREAD

**Issue by paulf81** [astral-sh/uv#8303]
On a shared cluster I am using, the only available install option for users to install uv at the moment is to pip install uv into a virtual environment, for example via:

```
python -m venv ~/uvevn
. ~/uvevn/bin/activate
pip install --upgrade --no-cache-dir pip
pip3 install uv
```
I can see how this method will work to have uv installed, but then isn't there a problem when I start wanting to use uv with seperate projects on that cluster, each with its own .venv folder, since I will need the `uvevn` environment activated to use uv.  Is the convention in cases like this to install uv separately into each project's virtual environment and then activate that environment?  Or is the convention to install uv into single virtual environment and then refer to uv without the virtual environment activated?

**Comment by bluss** [comment]
You don't need to activate the environment to call a binary installed there. This is true even for python scripts, and for uv. That means you can create an alias to uv where it is installed which is `~/uvevn/bin/uv` here. (Something that's particular to uv is that you can relocate it wherever you want after install. Just move both uv and uvx together so that they both work.)

**Comment by paulf81** [comment]
That makes a lot of sense, and good to know, thank you!

**Comment by bluss** [comment]
Other workarounds include: pip-install pipx then install uv using pipx. Pip install uv and then `uv tool install uv` to install uv again as a tool :)

**Comment by paulf81** [comment]
Thank you, this is very helpful!!
