### ISSUE TITLE
Running `uv sync --locked` asked to update uv.lock even after `uv lock`

### ISSUE THREAD

**Issue by ekzhu** [astral-sh/uv#8581]
To repreduce:

```
uv lock
uv sync --locked
```

```
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```

uv 0.4.27

**Comment by jackgerrits** [comment]
Issue should be reproducible on our workspace here:

https://github.com/microsoft/autogen/tree/main/python

**Comment by charliermarsh** [comment]
Thanks for the repro.

**Comment by charliermarsh** [comment]
Apologies. Fixed in the next release. You can also workaround it by removing the empty `dev-dependencies` list here (we weren't handling the empty case correctly when validating): https://github.com/microsoft/autogen/blob/3fe0f9e97d67a67f4027a92f458cb4842b3db43f/python/packages/autogen-agentchat/pyproject.toml#L22.

**Comment by jackgerrits** [comment]
Thanks so much for the quick fix and explanation!
