### ISSUE TITLE
`uv build`, `hatchling` and `ignore-vcs`

### ISSUE THREAD

**Issue by cofin** [astral-sh/uv#8833]
Thanks for the awesome tools.  I've been swapping our projects over to `uv` as time permits and it's really simplified our entire build and release process.

I have noticed one inconsistency though.  In one of our projects, I need to bundle static assets that are generated and stored in folder that is in the `.gitignore` file.

With other build tools, I've been able to explicitly add the assets to the to the [`artifacts`](https://hatch.pypa.io/latest/config/build/#artifacts) setting and they will be included in the final generated `whl` file.  

However, with `uv`, I've had to set the [`ignore-vcs`](https://hatch.pypa.io/latest/config/build/#artifacts) variable to make these assets be included in the final build.  

I'm on the `v0.4.30`, but I've seen this behavior in the last few releases as well.  Is this expected? 

The repository that I see this behavior in is not public, but if it would help, I can get an MVCE repo created.

Thanks

**Comment by charliermarsh** [comment]
I'm not 100% sure. Do you see the same behavior if you run `python -m build` (https://github.com/pypa/build)? That's basically the reference implementation for the spec.

**Comment by cofin** [comment]
> I'm not 100% sure. Do you see the same behavior if you run `python -m build` (https://github.com/pypa/build)? That's basically the reference implementation for the spec.

I'll double check and get back to you.

**Comment by cofin** [comment]
Interesting!

It looks like `python -m build` produces the same behavior as `uv build`.  I can only get the file included when the `ignore-vcs` setting is present.  However, the same projects did include them with with PDM and hatch.   

The current change of `ignore-vcs` is totally fine for me, so I think we can close this.  However, it's probably good to add share this anecdote I noticed when running these tests:  `artifacts` can be totally omitted from my build configuration when I enable the `ignore-vcs` setting.  The path I'm adding happens to be within the module.

I'll try to get some clarifications from the hatchling author as well.  The documentation is worded as if it is specifically for assets that have been ignored by [VCS](https://hatch.pypa.io/latest/config/build/#artifact). 

Thanks for the really quick response!

**Comment by cofin** [comment]
I wanted to close the loop on this.  I had a chance to chat with `ofek` and I figured out the difference here.  

I was using the top level configuration for `hatch` like so:
```toml
[tool.hatch.build]
dev-mode-dirs = ["."]
sources = ["."]
```

This type of declaration has been removed from the hatchling documentation.   The recommendation is to merge the settings needed into each build target instead.

Hopefully this will help others if this is encountered.

**Comment by charliermarsh** [comment]
Thanks for following up @cofin, appreciate it!

**Comment by espdev** [comment]
Hello @charliermarsh,

I have the same problem with hatch build. `uv build` just ignores `artifacts` and `force-include` rules.
For example, I have the following project structure:
```
.
├── pyproject.toml
├── .gitignore
├── src
│   └── artifacts_test
│       ├── __init__.py
│       └── foo.py
```

Where `foo.py` is added to `.gitignore` (the file is generated and should not be included to sdist, but should be included to wheel).

I adds the following rules to pyproject.toml:
```
[tool.hatch.build.targets.wheel]
artifacts = [
  "foo.py",
]
```

The Hatch [documentation says](https://hatch.pypa.io/1.9/config/build/#artifacts):
> If you want to include files that are [ignored by your VCS](https://hatch.pypa.io/1.9/config/build/#vcs), such as those that might be created by [build hooks](https://hatch.pypa.io/1.9/config/build/#build-hooks), you can use the artifacts option.

And it doesn't work with `uv build`. The file will not be added to the wheel package. Furthermore, if I want to add any files via [force-include](https://hatch.pypa.io/1.9/config/build/#forced-inclusion) that have been added to .gitignore, I get a build error.

For example, I adds `data/foo.log` file to the package root directory and adds the rules to pyproject.toml:

Add `data` to the project structure:
```
.
├── data
│   └── foo.log
```

Add `data/` to .gitignore
```
# artifacts test
foo.py
data/
```

pyproject.toml
```
[tool.hatch.build.targets.wheel.force-include]
"data" = "artifacts_test/data"
```

Try to call `uv build` and get an error "Forced include not found":
```
Building source distribution...
Building wheel from source distribution...
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/esp/.cache/uv/builds-v0/.tmpJxuHmR/lib/python3.10/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
  File "/home/esp/.cache/uv/builds-v0/.tmpJxuHmR/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
    artifact = version_api[version](directory, **build_data)
  File "/home/esp/.cache/uv/builds-v0/.tmpJxuHmR/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 477, in build_standard
    for included_file in self.recurse_included_files():
  File "/home/esp/.cache/uv/builds-v0/.tmpJxuHmR/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 177, in recurse_included_files
    yield from self.recurse_forced_files(self.config.get_force_include())
  File "/home/esp/.cache/uv/builds-v0/.tmpJxuHmR/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 237, in recurse_forced_files
    raise FileNotFoundError(msg)
FileNotFoundError: Forced include not found: /home/esp/.cache/uv/sdists-v9/.tmpP5E9AJ/artifacts_test-0.1.0/data
  × Failed to build `/home/esp/tmp/artifacts-test`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `hatchling.build.build_wheel` failed (exit status: 1)
      hint: This usually indicates a problem with the package or the build environment.
```

This seems to be because the files specified in .gitignore are simply not copied to the temporary directory from which the packages are built.

At the same time `uv build --wheel` seems to be working correctly. It creates a wheel file with all included artifacts without any errors. This seems to me to be incorrect behavior. `uv build` should not ignore the Hatch rules in `pyproject.toml`.

**Comment by konstin** [comment]
Is it `artifacts` or `artifacts_test`?

Your problem is with the hatchling configuration, this is not tied to `uv build`, but will happen with any source tree -> source dist -> wheel build.

**Comment by espdev** [comment]
> Is it artifacts or artifacts_test?

I don't quite understand your question.
artifacts_test is the name of the test project. Just for example. It doesn't make any difference.

What's wrong with the hatch configuration?

I thought build for each target should use the configuration for that target. I don't understand why `build` doesn't use the configuration for the wheel when it builds the wheel. Where should I specify the configuration for wheel in such a case?

It seems to me it violates [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by gitsandi** [comment]
I had the same problem.
`*.mo` files are specified in `.gitignore`, but I want them included in the wheel
For configuration
```
[tool.hatch.build.targets.sdist]
packages = [
    "testmodule"
]

[tool.hatch.build.targets.wheel]
artifacts = [
    "*.mo",
]
packages = [
    "testmodule"
]
```
- running `uv build` doesn't include `.mo` files in the wheel
- running `uv build --wheel` includes `.mo` files in the wheel

I'm not sure if the problem is in `uv` or `hatchling`, or maybe this is intended behavior (although confusing).

I solved the problem by moving `artifacts` option to `[tool.hatch.build]`: (maybe this will be of interest to [@cofin](https://github.com/cofin) and [@espdev](https://github.com/espdev))
```
[tool.hatch.build]
artifacts = [
    "*.mo",
]

[tool.hatch.build.targets.sdist]
packages = [
    "testmodule"
]

[tool.hatch.build.targets.wheel]
packages = [
    "testmodule"
]
```
With this configuration `uv build` includes `.mo` files both in wheel and in `tar.gz` . No need to use option `ignore-vcs = true`.
