### ISSUE TITLE
Corrupted `uv.lock` File Prevents Update with `uv lock` and `uv sync`

### ISSUE THREAD

**Issue by kiasari** [astral-sh/uv#8912]
uv 0.4.29
`uv lock` and `uv sync` can't update `uv.lock` file if a corrupted `uv.lock` exists.

**Comment by charliermarsh** [comment]
What would you expect to happen here? (And do you know how the `uv.lock` was corrupted?)

**Comment by kiasari** [comment]
Similar to the process when no lock file exists, it should ideally generate a new `uv.lock` file to replace the corrupted one. The lock file is corrupted since both `uv lock` and `uv sync` return `error: Failed to parse uv.lock`.

**Comment by charliermarsh** [comment]
I think silently ignoring that lock like that seems a little dubious -- if it's due to a merge conflict, we'd basically throw away the merge conflict, which would be wrong. Cargo for example will error if you have a corrupt lockfile. It seems reasonable to me to expect the user to just `rm uv.lock`.

**Comment by jgehrcke** [comment]
> It seems reasonable to me to expect the user to just rm uv.lock.

Agree. A "corrupt" lockfile is an exceptional event and I want to know when this happens.

**Comment by kiasari** [comment]
After accidentally modifying the `uv.lock` file in Vim, I noticed that `uv sync` and `uv lock` stopped working and I had to delete the lock file.

**Comment by charliermarsh** [comment]
Comfortable with our current behavior though acknowledge that there's subjectivity here.
