### ISSUE TITLE
Why `dependency-groups` and not `project.optional-dependencies`? (PEP 621)

### ISSUE THREAD

**Issue by d3cryptofc** [astral-sh/uv#8981]
I'm using `uv 0.4.30` version, and comparing the generated by UV `pyproject.toml` between [PEP 621](https://peps.python.org/pep-0621/#dependencies-optional-dependencies) I found this difference.

I just would like more details about it. Thank you!!

**Comment by ryanhiebert** [comment]
Optional dependencies are also supported. They are intended for library consumers to install optional packages, and are a public interface because of that. I've used them a lot of times as a hack to collect things that aren't for consumers but for me as a library developer, such as installing linters or pytest.

With dependency-groups, I can have `build` or `test` dependencies that I can install without exposing those to users in any public interface. `dependency-groups` are also a PEP, [PEP 735](https://peps.python.org/pep-0735/).

**Comment by charliermarsh** [comment]
Yeah, for local development, they're effectively identical in uv. The main difference from that perspective is that `optional-dependencies` are part of the _published_ metadata for your package, while `dependency-groups` are _only_ visible when working with your package locally. For example, if your package is `foo`, and you have an optional group called `bar` and a dependency group called `baz`, when you publish to PyPI, users can `uv pip install foo[bar]` (but `uv pip install foo[baz]` would error).

There are some other differences that are articulated in the PEP. For example, you can use `dependency-groups` without a `[project]` table, while `optional-dependencies` requires a `[project]` table. But that doesn't affect uv much right now since `uv lock`, `uv sync`, etc. all require projects.
