### ISSUE TITLE
`tool_run_cache` is flaky on Windows

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#9137]
See: https://github.com/astral-sh/uv/actions/runs/11847662623/job/33017797151?pr=9136

![Screenshot 2024-11-14 at 7 24 52 PM](https://github.com/user-attachments/assets/6bb8d655-a4d4-4eb4-b904-8a5b23c71a01)

**Comment by zanieb** [comment]
This seems to be new, I hadn't seen it before.

**Comment by konstin** [comment]
It's failing a lot: https://github.com/astral-sh/uv/actions/runs/11853487114/job/33034634717

**Comment by charliermarsh** [comment]
(I saw it at least once this week prior to reporting here.)

**Comment by zanieb** [comment]
Me too, but not prior to this week.

**Comment by charliermarsh** [comment]
I sort of have no idea what could be flaking here.

**Comment by FishAlchemist** [comment]
Although the reason is unknown, the temporary environment used in the first and second ``uv tool run`` might be different. While this has little impact on usage due to the rapid environment setup, it can still lead to a certain probability of test failure.

My guess is that this PR(https://github.com/astral-sh/uv/pull/9106) included the problem, as it wasn't there before. However, I can't say for sure since this issue is not always reproducible.
