### ISSUE TITLE
Should lock file be committed to source control?

### ISSUE THREAD

**Issue by ngaloppo** [astral-sh/uv#9797]
Seems like a basic question, but can't find this information in the documentation.

**Comment by zanieb** [comment]
Yep! https://docs.astral.sh/uv/guides/projects/#uvlock

**Comment by ngaloppo** [comment]
Thanks!!

**Comment by IllarionovDimitri** [comment]
@zanieb is the recommendation to commit uv.lock is similar for application and libs? 

from cargo/rust ecosystem i know that:

- Things that produce a final product, namely applications and binaries, should commit Cargo.lock to ensure a deterministic build.
- Library crates should not commit a Cargo.lock file, because it’s irrelevant to any downstream consumers of the library—they will have their own Cargo.lock file;  Cargo.lock file for a library crate is ignored by library users.

what would be your suggestion?

**Comment by Avasam** [comment]
> * Library crates should not commit a Cargo.lock file, because it’s irrelevant to any downstream consumers of the library—they will have their own Cargo.lock file;  Cargo.lock file for a library crate is ignored by library users.
> 
> 
> what would be your suggestion?

Depends if you care about your CI randomly breaking due to unprompted library updates.
Also, supply chain attacks.

You can use tools like Renovate and Dependabot to batch upgrade your dependencies once in a while, testing for new breakage, without affecting your working workflow.

For libraries, I personally like testing against locked deps + (newest resolution + age gating.) And having a second round of tests against (no lock + age gating) lowest-direct resolution.
