### ISSUE TITLE
use uv together with pip install -e

### ISSUE THREAD

**Issue by ghost** [astral-sh/uv#9904]
is it possible to use uv together with pip install -e

**Comment by neutrinoceros** [comment]
Yes. A couple notes:
- `pip` (or pip-tools) isn't available by default in an env created via `uv venv`, but you can get it via `uv pip install pip`
- `uv pip tree` includes packages installed via regular `pip`
- if you meant to ask if `uv pip install` supported the `-e/--editable` flag, the answer is also yes

I don't personally have a use for `pip` since switching to `uv`, but the few ways I can *think* of combining both appear to work seamlessly.
