### ISSUE TITLE
How to set environment variables

### ISSUE THREAD

**Issue by michaelxiacs** [astral-sh/uv#9951]
How do I set environment variables for the virtual environment created by UV? I tried setting it ```.venv/scripts/activate_this.py``` and it doesn't work.

```
# activate_this.py

...
os.environ["PATH"] = os.pathsep.join([bin_dir, *os.environ.get("PATH", "").split(os.pathsep)])
os.environ["VIRTUAL_ENV"] = base  # virtual env is right above bin directory
os.environ["VIRTUAL_ENV_PROMPT"] = "uv-demo" or os.path.basename(base)  # noqa: SIM222
os.environ["HELLO"] = "WORLD"
...

**Comment by samypr100** [comment]
Are you perhaps looking for a `.env` file instead? If the desire is to activate environment variables for your project, there's many solutions out there that can help you in doing so such as [direnv](https://direnv.net) rather than relying on virtualenv activation mechanisms setting additional environment variables for you.

**Comment by michaelxiacs** [comment]
I found my answer down below
https://docs.astral.sh/uv/configuration/files/#env
