### ISSUE TITLE
Adding option to generate uv.lock file without the Development dependencies

### ISSUE THREAD

**Issue by borisgurzhovski-itgma** [astral-sh/uv#9967]
Is it possible (maybe add it as future improvement) to add an option to generate an `uv.lock` file which won't include the Development dependencies?
 
Something similar to the `--no-dev` option, that won't install the Development dependencies when runing `uv run` or `uv sync`, but this will generate the `uv.lock` without them.

I am running the version 0.5.6
On a Docker container from python:3.9.20-slim-bookworm image
Command I am running is  `uv.lock` (full command is: `docker run -it --rm --volume "$PWD":/app DOCKER_NAME uv lock`)

Verbose output is:
`DEBUG uv 0.5.6`
`DEBUG Found workspace root: '/app'`
`DEBUG Adding current workspace member: '/app'`
`DEBUG Reading Python requests from version file at '/app/.python-version'`
`DEBUG Using Python request '3.9.20' from version file at '.python-version'`
`DEBUG The virtual environment's Python version satisfies '3.9.20'`
`DEBUG Using request timeout of 30s`
`DEBUG Found static 'pyproject.toml' for: xxx @ file:///app`
`DEBUG No workspace root found, using project root`
`DEBUG Existing 'uv.lock' satisfies workspace requirements`
 
Thanks in advance.

**Comment by charliermarsh** [comment]
What's the motivation for omitting development dependencies from the lockfile itself?

**Comment by borisgurzhovski-itgma** [comment]
Hi Charlie, thank you for your reply. 

I think it will be more clear/better overview of the file, if the development dependencies are not in the lock file.
Anyway this is just my perspective.

Thank you for your time.

**Comment by charliermarsh** [comment]
Got it! I'm going to pass on this suggestion for now as I think it makes sense to lock with the dev dependencies regardless.

**Comment by snoweuph** [comment]
How was this implemented, can't find the doc, and It's closed as completed.

My usecase for a lockfile without dev dependencies is to let Gitlab generate an SBOM without them (as dev Dependencies don't make sense in an SBOM after all)

if it isn't actually implemented, how about allowing `uv export` to also export to the `uv.lock` format. (because it doesn't seem to be able to do that rn)

```sh
$ uv --version
uv 0.8.8


$ uv export --no-dev --help
Export the project's lockfile to an alternate format

Usage: uv export [OPTIONS]

Options:
      --format <FORMAT>                    The format to which `uv.lock` should be exported [possible values: requirements.txt,
                                           pylock.toml]
```

**Comment by hasansezertasan** [comment]
> How was this implemented, can't find the doc, and It's closed as completed.

Checkout @charliermarsh's https://github.com/astral-sh/uv/issues/9967#issuecomment-2563723505.

> My usecase for a lockfile without dev dependencies is to let Gitlab generate an SBOM without them (as dev Dependencies don't make sense in an SBOM after all)
> 
> if it isn't actually implemented, how about allowing `uv export` to also export to the `uv.lock` format. (because it doesn't seem to be able to do that rn)
> 
> $ uv --version
> uv 0.8.8
> 
> 
> $ uv export --no-dev --help
> Export the project's lockfile to an alternate format
> 
> Usage: uv export [OPTIONS]
> 
> Options:
>       --format <FORMAT>                    The format to which `uv.lock` should be exported [possible values: requirements.txt,
>                                            pylock.toml]

Checkout the docs. [I think it's what you are looking for](https://docs.astral.sh/uv/concepts/projects/sync/#exporting-the-lockfile).

**Comment by nikohunt** [comment]
I'd like to revisit this request from a security and deployment perspective rather than a lockfile readability perspective.

I understand and generally agree with the rationale that `uv.lock` should represent the complete resolved graph for the project, including development dependency groups. A single canonical lockfile has clear benefits for reproducibility and avoiding resolution drift between environments.

However, we're increasingly seeing tooling consume `uv.lock` as a deployment artefact rather than solely as a resolver artefact.

One example is vulnerability and SBOM tooling. In our case, AWS Inspector scans the `uv.lock` file present in a container image and reports vulnerabilities from packages listed there, even when those packages belong exclusively to development dependency groups and are not installed in the runtime image.

In our case, `uv.lock` is present in the container image because a `COPY . .` brings it in during the build stage - a common pattern. While multi-stage builds can avoid this, many projects and base-image patterns don't use them, and the lockfile remains the artefact that vulnerability scanners treat as authoritative.

This creates many false positives, where the reported vulnerability surface does not match the actual deployed software. The current workaround is to manually modify or regenerate lockfiles during container builds, which is easy to forget and adds complexity to otherwise straightforward Docker workflows.

I'm not advocating for maintaining two independently resolved lockfiles. I can see how that could introduce consistency and dependency resolution challenges. Instead, would it be possible to support generation of a derived production-only lock artefact from the canonical `uv.lock`?
For example:
```
uv export --format uv-lock --no-dev
```
Or
```
uv lock --runtime-only
```
where the output is filtered from the already-resolved graph rather than independently resolved.

This would preserve:
• A single authoritative lockfile.
• Consistent dependency resolution.

While also enabling:
• More accurate vulnerability scanning.
• Better alignment between what is scanned and what is deployed.
• Reduced need for custom Dockerfile workarounds.

I suspect this problem will become more common as security tooling increasingly treats lockfiles as authoritative sources for software inventory. From that perspective, a production-focused lockfile export feels less like a packaging feature and more like an interoperability feature for downstream security ecosystems.

A runtime-only lockfile generated during CI that's checked into the repo or published as a build artefact is fundamentally different from a command that filters `uv.lock` during image creation. The latter is ephemeral and requires every Dockerfile author to remember lockfile hygiene. The former produces a versioned, auditable artefact that can be copied directly into production images, validated in CI alongside the canonical lockfile, and consumed by vulnerability scanners without any build-time transformation.
