### ISSUE TITLE
Isolate uv virtual environment from the system python

### ISSUE THREAD

**Issue by brunorigal** [astral-sh/uv#9993]
I created a virtual environment for my package using uv sync. The virtual environment is activated. And the library is missing the pytest package. Nevertheless, I can still access the pytest library installed in the system version of python. I would rather have a missing pytest error, because the uv run pytest command cannot access the virtual env and fail in a misleading way.

```bash
(docparser) brigal@675c178416a6:/workspace/docparser$ uv run which pytest
/usr/local/bin/pytest
(docparser) brigal@675c178416a6:/workspace/docparser$ echo $VIRTUAL_ENV
/workspace/docparser/.venv
(docparser) brigal@675c178416a6:/workspace/docparser$ uv run which python
/workspace/docparser/.venv/bin/python
```
Is there a reason why the uv venv are not isolated from the system python? Is there a parameter to solve this?

**Comment by nathanscain** [comment]
`uv run` puts the venv earlier on the `PATH`; however, it doesn't fully replace the `PATH`. This is because you sometimes need to run venv-aware system commands (think `make` or even `which` like your example)

Since there is no way to tell that /usr/local/bin/pytest *could have been* a venv managed executable in a general way, this has the current behavior. Changing this would require that `uv` be aware of all possible executables produced by **any** package which would be very slow, unexpected, and likely break workflows as I'm sure some package overrides `make`.

Maybe a warning for certain common cases could be added, but I'd favor the current behavior.

**Comment by brunorigal** [comment]
It sounds reasonable. Thanks for the explanation.

**Comment by nathanscain** [comment]
Happy to help 🤙
